#!/usr/bin/env python3
# ponytail: one-shot PNG -> Adafruit_GFX 1-bit PROGMEM converter.
# Thresholds the alpha channel (>=128 = set bit) and packs rows MSB-first,
# padded to whole bytes per row -- exactly what canvas->drawBitmap() expects.
# Run:  python icons/convert.py   (from repo root)
# Writes: W5/icons.h
import os
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS_DIR = os.path.join(REPO, "W5", "icons")
OUT = os.path.join(REPO, "W5", "icons.h")
WEATHER_OUT = os.path.join(REPO, "W5", "weather_icons.h")

# (file, C symbol) for each menu icon, in MenuManager.cpp MENU_ITEMS order.
ICON_SPECS = [
    ("watch.png",  "WATCH"),
    ("timer.png",  "TIMER"),   # Stopwatch
    ("timer-reset.png", "POMODORO"),  # Pomodoro timer
    ("weather/cloud-sun.png", "CLOUD_SUN"),  # Weather
    ("cog.png",    "COG"),     # Configuration
    ("wifi.png",   "WIFI"),    # WiFi status (not a menu item, but shares the pipeline)
]
SIZES = [48, 32]   # selected tier, near tier (far tier = text only, no icon)

# Weather icons: (filename, C symbol) — 32x32 1-bit for the weather screen.
WEATHER_ICON_SPECS = [
    ("sun.png",             "SUN"),
    ("cloud-sun.png",       "CLOUD_SUN"),
    ("cloud.png",           "CLOUD"),
    ("cloudy.png",          "CLOUDY"),
    ("cloud-fog.png",      "FOG"),
    ("cloud-drizzle.png",  "DRIZZLE"),
    ("cloud-rain.png",     "RAIN"),
    ("cloud-rain-wind.png","RAIN_WIND"),
    ("cloud-sun-rain.png", "SUN_RAIN"),
    ("cloud-snow.png",     "SNOW"),
    ("snowflake.png",      "SNOWFLAKE"),
    ("cloud-hail.png",     "HAIL"),
    ("cloud-lightning.png","LIGHTNING"),
    ("cloud-moon-rain.png","MOON_RAIN"),
]
WEATHER_ICON_SIZE = 32

# Battery icons: (filename, C symbol) — 24x24 1-bit for the watch face.
# Native size, no resize. drawBitmap(x,y,bm,24,24,color) recolors via color.
BATTERY_ICON_SPECS = [
    ("battery.png",          "BATTERY_EMPTY"),
    ("battery-low.png",      "BATTERY_LOW"),
    ("battery-medium.png",   "BATTERY_MEDIUM"),
    ("battery-full.png",     "BATTERY_FULL"),
    ("battery-charging.png", "BATTERY_CHARGING"),
]
BATTERY_ICON_SIZE = 32

# Legend icons: (filename, C symbol) — 12x12 1-bit for the weather screen legend.
# Sized to match the old 12x12 precipitation swatch so screen real estate is unchanged.
LEGEND_ICON_SPECS = [
    ("droplets.png",    "DROPLETS"),     # precipitation (was blue square)
    ("thermometer.png", "THERMOMETER"),  # temperature (was red line)
    ("map-pin.png",     "MAP_PIN"),      # location marker (new, beside city name)
]
LEGEND_ICON_SIZE = 12

def pack_1bit(im_luma):
    """im_luma: PIL 'L' mode. Return list of bytes, MSB-first, row-padded."""
    w, h = im_luma.size
    px = im_luma.load()
    out = []
    bytes_per_row = (w + 7) // 8
    for y in range(h):
        for byte_idx in range(bytes_per_row):
            b = 0
            for bit in range(8):
                x = byte_idx * 8 + bit
                if x < w and px[x, y] >= 128:
                    b |= 0x80 >> bit
            out.append(b)
    return out

def emit_array(name, w, h, data):
    lines = [f"static const unsigned char PROGMEM {name}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02X}")
        if len(row) == 12:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row))
    lines.append("};")
    return "\n".join(lines)

def main():
    chunks = [
        "// AUTO-GENERATED by icons/convert.py -- do not edit by hand.",
        "// 1-bit mono icons for the arc carousel. drawBitmap(x,y,bm,w,h,color)",
        "// recolors via the `color` arg, so icons dim/brighten with the text.",
        "#ifndef ICONS_H",
        "#define ICONS_H",
        "#include <Arduino.h>",
        "",
    ]
    # Emit one array per (icon, size): NAME_24, NAME_16
    for fname, sym in ICON_SPECS:
        path = os.path.join(ICONS_DIR, fname)
        if not os.path.exists(path):
            print(f"  SKIP missing: {fname}")
            continue
        im = Image.open(path).convert("RGBA")
        # Use alpha as the mask (glyphs are single-color black on transparent).
        # Split alpha into its own 'L' image as the 1-bit source.
        alpha = im.getchannel("A")
        for size in SIZES:
            g = alpha.resize((size, size), Image.LANCZOS)
            data = pack_1bit(g)
            chunks.append(emit_array(f"ICON_{sym}_{size}", size, size, data))
            chunks.append("")
    # Lookup helper: returns the PROGMEM array + dims for a menu label index,
    # or nullptr when there is no icon for that index. Sizes are data-driven
    # from SIZES so the lookup can't drift from the emitted arrays.
    labels = ["Watch", "Stopwatch (timer glyph)", "Pomodoro", "Weather (cloud-sun)", "Configuration (cog glyph)", "WiFi (status indicator)"]
    chunks += [
        "// labelIdx: 0=Watch, 1=Stopwatch(timer), 2=Pomodoro, 3=Weather(cloud-sun), 4=Configuration(cog), 5=WiFi(status)",
        "inline const unsigned char* menuIconBitmap(uint8_t labelIdx, uint8_t size,",
        "                                        uint8_t* outW, uint8_t* outH) {",
        "  switch (labelIdx) {",
    ]
    for i, (_, sym) in enumerate(ICON_SPECS):
        chunks.append(f"    case {i}:  // {labels[i]}")
        for s in SIZES:
            chunks.append(
                f"      if (size == {s}) {{ *outW = {s}; *outH = {s}; return ICON_{sym}_{s}; }}"
            )
        chunks.append("      break;")
    chunks += [
        "  }",
        "  *outW = 0; *outH = 0;",
        "  return nullptr;",
        "}",
        "",
        "#endif  // ICONS_H",
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(chunks) + "\n")
    print(f"Wrote {OUT}")

    # ---- Weather icons ----
    weather_dir = os.path.join(REPO, "W5", "icons", "weather")
    wchunks = [
        "// AUTO-GENERATED by icons/convert.py -- do not edit by hand.",
        "// 1-bit mono weather icons (32x32). drawBitmap(x,y,bm,32,32,color)",
        "#ifndef WEATHER_ICONS_H",
        "#define WEATHER_ICONS_H",
        "#include <Arduino.h>",
        "",
    ]
    for fname, sym in WEATHER_ICON_SPECS:
        path = os.path.join(weather_dir, fname)
        if not os.path.exists(path):
            print(f"  SKIP missing: {fname}")
            continue
        im = Image.open(path).convert("RGBA")
        alpha = im.getchannel("A")
        g = alpha.resize((WEATHER_ICON_SIZE, WEATHER_ICON_SIZE), Image.LANCZOS)
        data = pack_1bit(g)
        wchunks.append(emit_array(f"WICON_{sym}", WEATHER_ICON_SIZE, WEATHER_ICON_SIZE, data))
        wchunks.append("")

    # Lookup: weather code -> icon bitmap
    wchunks += [
        "// Maps open-meteo weathercode to the appropriate icon bitmap.",
        "inline const unsigned char* weatherIconBitmap(int code,",
        "                                           uint8_t* outW, uint8_t* outH) {",
        "  const unsigned char* bm = WICON_SUN; // default",
        "  if (code == 0)",
        "    bm = WICON_SUN;",
        "  else if (code == 1 || code == 2)",
        "    bm = WICON_CLOUD_SUN;",
        "  else if (code == 3)",
        "    bm = WICON_CLOUDY;",
        "  else if (code == 45 || code == 48)",
        "    bm = WICON_FOG;",
        "  else if (code >= 51 && code <= 57)",
        "    bm = WICON_DRIZZLE;",
        "  else if (code >= 61 && code <= 65)",
        "    bm = WICON_RAIN;",
        "  else if (code == 66 || code == 67)",
        "    bm = WICON_RAIN_WIND;",
        "  else if (code == 71 || code == 73 || code == 75)",
        "    bm = WICON_SNOW;",
        "  else if (code == 77)",
        "    bm = WICON_SNOWFLAKE;",
        "  else if (code >= 80 && code <= 82)",
        "    bm = WICON_SUN_RAIN;",
        "  else if (code == 85 || code == 86)",
        "    bm = WICON_HAIL;",
        "  else if (code >= 95)",
        "    bm = WICON_LIGHTNING;",
        "  *outW = 32; *outH = 32;",
        "  return bm;",
        "}",
        "",
        "#endif  // WEATHER_ICONS_H",
    ]
    with open(WEATHER_OUT, "w", newline="\n") as f:
        f.write("\n".join(wchunks) + "\n")
    print(f"Wrote {WEATHER_OUT}")

    # ---- Battery icons ----
    battery_dir = os.path.join(ICONS_DIR, "battery")
    battery_out = os.path.join(REPO, "W5", "battery_icons.h")
    bchunks = [
        "// AUTO-GENERATED by icons/convert.py -- do not edit by hand.",
        "// 1-bit mono battery icons (24x24). drawBitmap(x,y,bm,24,24,color)",
        "#ifndef BATTERY_ICONS_H",
        "#define BATTERY_ICONS_H",
        "#include <Arduino.h>",
        "",
    ]
    for fname, sym in BATTERY_ICON_SPECS:
        path = os.path.join(battery_dir, fname)
        if not os.path.exists(path):
            print(f"  SKIP missing: {fname}")
            continue
        im = Image.open(path).convert("RGBA")
        alpha = im.getchannel("A")
        g = alpha.resize((BATTERY_ICON_SIZE, BATTERY_ICON_SIZE), Image.LANCZOS)
        data = pack_1bit(g)
        bchunks.append(emit_array(f"BATICON_{sym}", BATTERY_ICON_SIZE, BATTERY_ICON_SIZE, data))
        bchunks.append("")

    # Lookup: battery percentage -> icon bitmap
    bchunks += [
        "// Maps battery percentage to the appropriate icon bitmap.",
        "//   <=15%: low, 16-50%: medium, 51-100%: full",
        "inline const unsigned char* batteryIconBitmap(int pct, uint8_t* outW, uint8_t* outH) {",
        "  const unsigned char* bm;",
        "  if (pct <= 15)      bm = BATICON_BATTERY_LOW;",
        "  else if (pct <= 50) bm = BATICON_BATTERY_MEDIUM;",
        "  else                bm = BATICON_BATTERY_FULL;",
        f"  *outW = {BATTERY_ICON_SIZE}; *outH = {BATTERY_ICON_SIZE};",
        "  return bm;",
        "}",
        "",
        "#endif  // BATTERY_ICONS_H",
    ]
    with open(battery_out, "w", newline="\n") as f:
        f.write("\n".join(bchunks) + "\n")
    print(f"Wrote {battery_out}")

    # ---- Legend icons (weather screen) ----
    legend_out = os.path.join(REPO, "W5", "legend_icons.h")
    lchunks = [
        "// AUTO-GENERATED by icons/convert.py -- do not edit by hand.",
        f"// 1-bit mono legend icons ({LEGEND_ICON_SIZE}x{LEGEND_ICON_SIZE}). drawBitmap(x,y,bm,w,h,color)",
        "#ifndef LEGEND_ICONS_H",
        "#define LEGEND_ICONS_H",
        "#include <Arduino.h>",
        "",
    ]
    for fname, sym in LEGEND_ICON_SPECS:
        path = os.path.join(ICONS_DIR, fname)
        if not os.path.exists(path):
            print(f"  SKIP missing: {fname}")
            continue
        im = Image.open(path).convert("RGBA")
        alpha = im.getchannel("A")
        g = alpha.resize((LEGEND_ICON_SIZE, LEGEND_ICON_SIZE), Image.LANCZOS)
        data = pack_1bit(g)
        lchunks.append(emit_array(f"LICON_{sym}", LEGEND_ICON_SIZE, LEGEND_ICON_SIZE, data))
        lchunks.append("")
    lchunks += [
        "#endif  // LEGEND_ICONS_H",
    ]
    with open(legend_out, "w", newline="\n") as f:
        f.write("\n".join(lchunks) + "\n")
    print(f"Wrote {legend_out}")


if __name__ == "__main__":
    main()
