#!/usr/bin/env python3
# ponytail: one-shot PNG -> Adafruit_GFX 1-bit PROGMEM converter.
# Thresholds the alpha channel (>=128 = set bit) and packs rows MSB-first,
# padded to whole bytes per row -- exactly what canvas->drawBitmap() expects.
# Run:  python icons/convert.py   (from repo root)
# Writes: W5/icons.h
import os
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS_DIR = os.path.join(REPO, "W5", "icons")
OUT = os.path.join(REPO, "W5", "icons.h")

# (file, C symbol) for each menu icon, in MenuManager.cpp MENU_ITEMS order.
ICON_SPECS = [
    ("watch.png",  "WATCH"),
    ("timer.png",  "TIMER"),   # Stopwatch
    ("cog.png",    "COG"),     # Configuration
]
SIZES = [24, 16]   # selected tier, near tier (far tier = text only, no icon)

def pack_1bit(im_luma):
    """im_luma: PIL 'L' mode. Return list of bytes, MSB-first, row-padded."""
    w, h = im_luma.size
    px = im_luma.load()
    out = []
    bytes_per_row = (w + 7) // 8
    for y in range(h):
        for byte_idx in range(bytes_per_row):
            b = 0
            for bit in range(8):
                x = byte_idx * 8 + bit
                if x < w and px[x, y] >= 128:
                    b |= 0x80 >> bit
            out.append(b)
    return out

def emit_array(name, w, h, data):
    lines = [f"static const unsigned char PROGMEM {name}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02X}")
        if len(row) == 12:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row))
    lines.append("};")
    return "\n".join(lines)

def main():
    chunks = [
        "// AUTO-GENERATED by icons/convert.py -- do not edit by hand.",
        "// 1-bit mono icons for the arc carousel. drawBitmap(x,y,bm,w,h,color)",
        "// recolors via the `color` arg, so icons dim/brighten with the text.",
        "#ifndef ICONS_H",
        "#define ICONS_H",
        "#include <Arduino.h>",
        "",
    ]
    # Emit one array per (icon, size): NAME_24, NAME_16
    for fname, sym in ICON_SPECS:
        path = os.path.join(ICONS_DIR, fname)
        im = Image.open(path).convert("RGBA")
        # Use alpha as the mask (glyphs are single-color black on transparent).
        # Split alpha into its own 'L' image as the 1-bit source.
        alpha = im.getchannel("A")
        for size in SIZES:
            g = alpha.resize((size, size), Image.LANCZOS)
            data = pack_1bit(g)
            chunks.append(emit_array(f"ICON_{sym}_{size}", size, size, data))
            chunks.append("")
    # Lookup helper: returns the PROGMEM array + dims for a menu label index,
    # or nullptr when there is no icon for that index.
    chunks += [
        "// labelIdx: 0=Watch, 1=Stopwatch(timer), 2=Configuration(cog)",
        "inline const unsigned char* menuIconBitmap(uint8_t labelIdx, uint8_t size,",
        "                                        uint8_t* outW, uint8_t* outH) {",
        "  switch (labelIdx) {",
        "    case 0:  // Watch",
        "      if (size == 24) { *outW = 24; *outH = 24; return ICON_WATCH_24; }",
        "      if (size == 16) { *outW = 16; *outH = 16; return ICON_WATCH_16; }",
        "      break;",
        "    case 1:  // Stopwatch -> timer glyph",
        "      if (size == 24) { *outW = 24; *outH = 24; return ICON_TIMER_24; }",
        "      if (size == 16) { *outW = 16; *outH = 16; return ICON_TIMER_16; }",
        "      break;",
        "    case 2:  // Configuration -> cog glyph",
        "      if (size == 24) { *outW = 24; *outH = 24; return ICON_COG_24; }",
        "      if (size == 16) { *outW = 16; *outH = 16; return ICON_COG_16; }",
        "      break;",
        "  }",
        "  *outW = 0; *outH = 0;",
        "  return nullptr;",
        "}",
        "",
        "#endif  // ICONS_H",
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(chunks) + "\n")
    print(f"Wrote {OUT}")

if __name__ == "__main__":
    main()
