#!/usr/bin/env python3
"""Generate a 1-bit equirectangular Earth landmask header for the W5 watch.

Source: Natural Earth 110m Admin-0 Countries (CC0 / public domain), pre-tessellated
to a 360x170 grid (1 deg/cell, lat +85..-85, lon -180..+180) by the nimiq-simple-faucet
project. We fetch that .ts file, parse the LAND_BITMAP array, pack it MSB-first
row-padded (45 bytes/row x 170 rows = 7650 bytes), and emit W5/earth_landmask.h.

Run:  python icons/gen_earth_landmask.py   (from repo root)
Writes: W5/earth_landmask.h

On-device lookup (matches Adafruit_GFX 1-bit packing used elsewhere):
  col = lon_deg + 180        (0..359)
  row = 85 - lat_deg         (0..169, row 0 = +85 N)
  byte = EARTH_LANDMASK[row*45 + col/8]
  bit  = 0x80 >> (col & 7)   (set = land)
"""
import os
import re
import ssl
import sys
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "W5", "earth_landmask.h")
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_landmask_data.ts")

SOURCE_URL = ("https://raw.githubusercontent.com/PanoramicRum/nimiq-simple-faucet/"
              "main/apps/nimiq-pow-ui/src/lib/landmask-data.ts")

W, H, LAT_MAX = 360, 170, 85
BYTES_PER_ROW = (W + 7) // 8  # 45


def fetch_source():
    if os.path.exists(CACHE):
        print(f"Using cached source: {CACHE}")
        return open(CACHE, "r", encoding="utf-8").read()
    print(f"Fetching {SOURCE_URL} ...")
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "curl/8"})
    data = urllib.request.urlopen(req, context=ctx, timeout=30).read().decode("utf-8")
    open(CACHE, "w", encoding="utf-8").write(data)
    return data


def parse_bitmap(src):
    """Return a flat 61200-char string of '0'/'1', row-major (row 0 = +85 N)."""
    i = src.find("export const LAND_BITMAP = [")
    if i < 0:
        sys.exit("ERROR: LAND_BITMAP array not found in source")
    j = src.find("];", i)
    arr = src[i + len("export const LAND_BITMAP = ["):j]
    segs = re.findall(r"'([01]+)'", arr)
    flat = "".join(segs)
    if len(flat) != W * H:
        sys.exit(f"ERROR: parsed {len(flat)} cells, expected {W*H}")
    return flat


def pack_1bit(flat):
    """Pack row-major 0/1 string to MSB-first, row-padded bytes."""
    out = bytearray()
    for row in range(H):
        for byte_idx in range(BYTES_PER_ROW):
            b = 0
            for bit in range(8):
                col = byte_idx * 8 + bit
                if col < W and flat[row * W + col] == "1":
                    b |= 0x80 >> bit
            out.append(b)
    assert len(out) == BYTES_PER_ROW * H
    return out


def emit_array(name, data):
    lines = [f"static const unsigned char PROGMEM {name}[] = {{"]
    row = []
    for i, b in enumerate(data):
        row.append(f"0x{b:02X}")
        if len(row) == 12:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row))
    lines.append("};")
    return "\n".join(lines)


def main():
    src = fetch_source()
    flat = parse_bitmap(src)
    data = pack_1bit(flat)
    land = flat.count("1")
    chunks = [
        "// AUTO-GENERATED by icons/gen_earth_landmask.py -- do not edit by hand.",
        "// 1-bit equirectangular Earth landmask, 360x170 (1 deg/cell).",
        "// Source: Natural Earth 110m Admin-0 Countries (CC0 / public domain),",
        "// pre-tessellated by nimiq-simple-faucet (landmask-data.ts).",
        "//",
        "// Lookup:",
        "//   col = lon_deg + 180        (0..359)",
        "//   row = 85 - lat_deg         (0..169, row 0 = +85 N)",
        "//   byte = EARTH_LANDMASK[row*45 + col/8]",
        "//   bit  = 0x80 >> (col & 7)   (set = land)",
        f"// Size: {len(data)} bytes PROGMEM. Land cells: {land}/{len(flat)}.",
        "#ifndef EARTH_LANDMASK_H",
        "#define EARTH_LANDMASK_H",
        "#include <Arduino.h>",
        "#include <math.h> // floor()",
        "",
        f"#define EARTH_LANDMASK_W   {W}",
        f"#define EARTH_LANDMASK_H   {H}",
        f"#define EARTH_LANDMASK_LAT_MAX {LAT_MAX}",
        f"#define EARTH_LANDMASK_BPR {BYTES_PER_ROW}",
        "",
        emit_array("EARTH_LANDMASK", data),
        "",
        "// Returns true if (latDeg, lonDeg) is land. Out-of-range -> false (sea).",
        "inline bool earthIsLand(double latDeg, double lonDeg) {",
        "  while (lonDeg < -180.0) lonDeg += 360.0;",
        "  while (lonDeg >= 180.0) lonDeg -= 360.0;",
        "  int col = (int)floor(lonDeg + 180.0);",
        "  int row = EARTH_LANDMASK_LAT_MAX - (int)floor(latDeg);",
        "  if (col < 0 || col >= EARTH_LANDMASK_W) return false;",
        "  if (row < 0 || row >= EARTH_LANDMASK_H) return false;",
        f"  uint16_t bi = (uint16_t)row * EARTH_LANDMASK_BPR + (uint16_t)(col >> 3);",
        "  uint8_t bits = pgm_read_byte(&EARTH_LANDMASK[bi]);",
        "  return bits & (0x80 >> (col & 7));",
        "}",
        "",
        "#endif  // EARTH_LANDMASK_H",
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(chunks) + "\n")
    print(f"Wrote {OUT}  ({len(data)} bytes, {land}/{len(flat)} land cells)")


if __name__ == "__main__":
    main()
