#include "DisplayManager.h"
#include "BatteryManager.h"
#include "BluetoothManager.h"
#include "RM67162Display.h"
#include "MenuManager.h"
#include "StopwatchManager.h"
#include "TimeManager.h"
#include "WeatherManager.h"
#include "config/config.h" // LATITUDE / LONGITUDE for Dusk2Dawn
#include "Dusk2Dawn.h"
#include "starfield_icons.h" // 7-seg digits, am/pm, wifi (from watchy-starfield)
#include "earth_landmask.h" // 1-bit equirectangular landmask (generated by icons/gen_earth_landmask.py)
#include "sevenseg_letters.h" // 7-seg letter bitmaps (generated by icons/gen_7seg_letters.py)
#include "battery_icons.h" // 1-bit battery state icons (generated from icons/battery/*.png)
#include "icons.h" // 1-bit PROGMEM menu icons (generated from icons/*.png)
#include "weather_icons.h" // 1-bit PROGMEM weather icons (generated from icons/weather/*.png)
#include "rm67162.h" // For lcd_PushColors
#include <math.h>
#include <WiFi.h>

static RM67162Display display;
GFXcanvas16 *DisplayManager::canvas = nullptr;

// ----- Starfield watch face helpers -----
// Adapted from watchy-starfield-main: 7-seg digit bitmaps, moon phase,
// sunrise/sunset, procedural starfield background. Layout is landscape
// (536x240) instead of the original 200x200 portrait e-paper.

// ponytail: 16-bit LCG for a deterministic starfield. Same seed → same stars
// every frame, so the background is stable across redraws. Ceiling: stars
// are fixed at boot; no drift/twinkle. Upgrade: animate with millis().
static uint32_t s_starSeed = 0x1234ABCD;
static inline uint32_t lcg16() {
  s_starSeed = s_starSeed * 1103515245u + 12345u;
  return (s_starSeed >> 16) & 0x7FFF;
}

// Draw n deterministic stars onto the canvas. Sizes vary 1-2px for depth.
static void drawStarfield(GFXcanvas16 *c, int n) {
  s_starSeed = 0x1234ABCD; // reset for determinism
  for (int i = 0; i < n; i++) {
    int16_t x = (int16_t)(lcg16() % c->width());
    int16_t y = (int16_t)(lcg16() % c->height());
    uint8_t  r = (lcg16() & 1) ? 2 : 1;
    // Dim white/blue stars for depth — RGB565
    uint16_t col = (lcg16() & 3) == 0 ? 0xBDF7 : 0xFFFF; // 25% bluish, rest white
    if (r == 1)
      c->drawPixel(x, y, col);
    else
      c->fillCircle(x, y, 1, col);
  }
}

// 7-seg big digit (33x53) lookup. fd_0..fd_9 from starfield_icons.h.
static const unsigned char *fdDigits[] = {
  fd_0, fd_1, fd_2, fd_3, fd_4, fd_5, fd_6, fd_7, fd_8, fd_9
};
// 7-seg small digit (16x25) lookup. dd_0..dd_9
static const unsigned char *ddDigits[] = {
  dd_0, dd_1, dd_2, dd_3, dd_4, dd_5, dd_6, dd_7, dd_8, dd_9
};
// 3x5 tiny digit lookup. num_0..num_9
static const unsigned char *numDigits[] = {
  num_0, num_1, num_2, num_3, num_4, num_5, num_6, num_7, num_8, num_9
};

// Draw a multi-digit 7-seg number at (x,y) using big 33x53 bitmaps.
// Returns the total width drawn.
static int drawBigDigits(GFXcanvas16 *c, int value, int nDigits,
                         int16_t x, int16_t y, uint16_t color) {
  const int dw = 33, dh = 53, gap = 4;
  for (int i = nDigits - 1; i >= 0; i--) {
    int d = value % 10;
    value /= 10;
    int16_t dx = x + i * (dw + gap);
    c->drawBitmap(dx, y, fdDigits[d], dw, dh, color);
  }
  return nDigits * (dw + gap) - gap;
}

// Draw a multi-digit 7-seg number at (x,y) using small 16x25 bitmaps.
static int drawSmallDigits(GFXcanvas16 *c, int value, int nDigits,
                           int16_t x, int16_t y, uint16_t color) {
  const int dw = 16, dh = 25, gap = 3;
  for (int i = nDigits - 1; i >= 0; i--) {
    int d = value % 10;
    value /= 10;
    int16_t dx = x + i * (dw + gap);
    c->drawBitmap(dx, y, ddDigits[d], dw, dh, color);
  }
  return nDigits * (dw + gap) - gap;
}

// Draw a 3x5 tiny digit at (x,y) — used for sunrise/sunset HH:MM.
static void drawTinyDigits(GFXcanvas16 *c, int value, int nDigits,
                           int16_t x, int16_t y, uint16_t color) {
  const int dw = 3, dh = 5, gap = 1;
  for (int i = nDigits - 1; i >= 0; i--) {
    int d = value % 10;
    value /= 10;
    int16_t dx = x + i * (dw + gap);
    c->drawBitmap(dx, y, numDigits[d], dw, dh, color);
  }
}

// Draw small L-shaped corner brackets around a bounding box.
// leg = length of each L arm in pixels.
static void drawCornerBrackets(GFXcanvas16 *c, int16_t x, int16_t y,
                               int16_t w, int16_t h, uint8_t leg,
                               uint16_t color) {
  if (w < 2 || h < 2) return;
  int16_t rx = x + w - 1, by = y + h - 1;
  // Top-left
  c->drawFastHLine(x, y, leg, color);
  c->drawFastVLine(x, y, leg, color);
  // Top-right
  c->drawFastHLine(rx - leg + 1, y, leg, color);
  c->drawFastVLine(rx, y, leg, color);
  // Bottom-left
  c->drawFastHLine(x, by, leg, color);
  c->drawFastVLine(x, by - leg + 1, leg, color);
  // Bottom-right
  c->drawFastHLine(rx - leg + 1, by, leg, color);
  c->drawFastVLine(rx, by - leg + 1, leg, color);
}

// Draw a 1-bit PROGMEM bitmap scaled by `sx`/`sy` (float for fine control).
// Used to make the 33x53 7-seg digits fill the top half of the screen, and
// to scale moon/icons by fractional amounts. fillRect per set pixel.
static void drawBitmapScaled(GFXcanvas16 *c, int16_t x, int16_t y,
                             const unsigned char *bm, int16_t w, int16_t h,
                             float sx, float sy, uint16_t color) {
  int16_t bytesPerRow = (w + 7) / 8;
  for (int16_t row = 0; row < h; row++) {
    for (int16_t col = 0; col < w; col++) {
      uint16_t byteIdx = row * bytesPerRow + col / 8;
      uint8_t bits = pgm_read_byte(&bm[byteIdx]);
      if (bits & (0x80 >> (col & 7))) {
        int16_t px = (int16_t)(col * sx);
        int16_t py = (int16_t)(row * sy);
        int16_t ex = (int16_t)((col + 1) * sx);
        int16_t ey = (int16_t)((row + 1) * sy);
        c->fillRect(x + px, y + py, ex - px, ey - py, color);
      }
    }
  }
}

// Draw n 33x53 7-seg digits scaled by `scale`, with `gap` px between digits.
static void drawBigDigitsScaled(GFXcanvas16 *c, int value, int nDigits,
                                int16_t x, int16_t y, int scale, int gap,
                                uint16_t color) {
  const int dw = 33, dh = 53;
  int step = dw * scale + gap;
  for (int i = nDigits - 1; i >= 0; i--) {
    int d = value % 10;
    value /= 10;
    drawBitmapScaled(c, x + i * step, y, fdDigits[d], dw, dh, scale, scale, color);
  }
}

// Width of a 7-seg string (big 33x53, scaled). Same advance as drawBigText7seg.
static int bigText7segWidth(const char *s, int scale, int gap) {
  const int dw = 33;
  int step = dw * scale + gap;
  int n = 0;
  for (const char *p = s; *p; p++) n++;
  return n > 0 ? n * step - gap : 0;
}

// Draw a mixed alphanumeric 7-seg string using big 33x53 bitmaps, scaled.
// Handles digits 0-9, letters/punctuation from sevenseg_letters.h, ':'
// (two round dots via fillCircle for cleaner look), and ' ' (gap).
// Returns total width drawn. Unknown chars are skipped (zero width).
static int drawBigText7seg(GFXcanvas16 *c, const char *s,
                           int16_t x, int16_t y, int scale, int gap,
                           uint16_t color) {
  const int dw = 33, dh = 53;
  int step = dw * scale + gap;
  int16_t cx = x;
  for (const char *p = s; *p; p++) {
    char ch = *p;
    if (ch == ' ') { cx += step; continue; }
    if (ch == ':') {
      int16_t cy1 = y + dh * scale / 3;
      int16_t cy2 = y + dh * scale * 2 / 3;
      uint8_t r = scale >= 2 ? 2 * scale / 3 : 1;
      c->fillCircle(cx + dw * scale / 2, cy1, r, color);
      c->fillCircle(cx + dw * scale / 2, cy2, r, color);
      cx += step;
      continue;
    }
    const unsigned char *bm = nullptr;
    if (ch >= '0' && ch <= '9') bm = fdDigits[ch - '0'];
    else                        bm = fd_letterBitmap(ch);
    if (!bm) continue;
    drawBitmapScaled(c, cx, y, bm, dw, dh, scale, scale, color);
    cx += step;
  }
  return cx - x - gap;
}

// Width of a 7-seg string (small 16x25). Same advance as drawSmallText7seg.
static int smallText7segWidth(const char *s, int gap) {
  const int dw = 16;
  int step = dw + gap;
  int n = 0;
  for (const char *p = s; *p; p++) n++;
  return n > 0 ? n * step - gap : 0;
}

// Draw a mixed alphanumeric 7-seg string using small 16x25 bitmaps.
// Returns total width drawn. Unknown chars are skipped.
static int drawSmallText7seg(GFXcanvas16 *c, const char *s,
                             int16_t x, int16_t y, int gap,
                             uint16_t color) {
  const int dw = 16, dh = 25;
  int step = dw + gap;
  int16_t cx = x;
  for (const char *p = s; *p; p++) {
    char ch = *p;
    if (ch == ' ') { cx += step; continue; }
    if (ch == ':') {
      c->fillCircle(cx + dw / 2, y + dh / 3, 2, color);
      c->fillCircle(cx + dw / 2, y + dh * 2 / 3, 2, color);
      cx += step;
      continue;
    }
    const unsigned char *bm = nullptr;
    if (ch >= '0' && ch <= '9') bm = ddDigits[ch - '0'];
    else                        bm = dd_letterBitmap(ch);
    if (!bm) continue;
    c->drawBitmap(cx, y, bm, dw, dh, color);
    cx += step;
  }
  return cx - x - gap;
}

// Draw small 16x25 7-seg text scaled by an integer factor (via drawBitmapScaled).
// For when you need the small font bigger but don't want the big 33x53 font.
static int drawSmallText7segScaled(GFXcanvas16 *c, const char *s,
                                   int16_t x, int16_t y, int scale, int gap,
                                   uint16_t color) {
  const int dw = 16, dh = 25;
  int step = dw * scale + gap;
  int16_t cx = x;
  for (const char *p = s; *p; p++) {
    char ch = *p;
    if (ch == ' ') { cx += step; continue; }
    if (ch == ':') {
      uint8_t r = scale >= 2 ? scale : 1;
      c->fillCircle(cx + dw * scale / 2, y + dh * scale / 3, r, color);
      c->fillCircle(cx + dw * scale / 2, y + dh * scale * 2 / 3, r, color);
      cx += step;
      continue;
    }
    const unsigned char *bm = nullptr;
    if (ch >= '0' && ch <= '9') bm = ddDigits[ch - '0'];
    else                        bm = dd_letterBitmap(ch);
    if (!bm) continue;
    drawBitmapScaled(c, cx, y, bm, dw, dh, scale, scale, color);
    cx += step;
  }
  return cx - x - gap;
}

static int smallText7segScaledWidth(const char *s, int scale, int gap) {
  const int dw = 16;
  int step = dw * scale + gap;
  int n = 0;
  for (const char *p = s; *p; p++) n++;
  return n > 0 ? n * step - gap : 0;
}

// --- 7-seg text rendering (replaces former dot-matrix renderer) ---
// Maps a `size` param to the closest 7-seg font/scale. The 7-seg font has a
// different aspect ratio than the old dot-matrix font, so heights won't match
// exactly — layouts may need minor y adjustment.
//   size 1   → tiny  8x12  (gap 1)
//   size 2-3 → small 16x25 (gap 2-3)
//   size 4-5 → small 16x25 scaled 2x (gap 3)
//   size 6+  → big   33x53 (gap 4)
static void drawText7seg(GFXcanvas16 *c, const char *s, int16_t x, int16_t y,
                         uint8_t size, uint16_t color) {
  if (!c || !s || !*s) return;
  if (size <= 1) {
    // tiny 8x12 font
    const int dw = 8, dh = 12, gap = 1;
    int step = dw + gap;
    int16_t cx = x;
    for (const char *p = s; *p; p++) {
      char ch = *p;
      if (ch == ' ') { cx += step; continue; }
      if (ch == ':') {
        c->fillCircle(cx + dw / 2, y + dh / 3, 1, color);
        c->fillCircle(cx + dw / 2, y + dh * 2 / 3, 1, color);
        cx += step;
        continue;
      }
      const unsigned char *bm = td_letterBitmap(ch);
      if (!bm) continue;
      c->drawBitmap(cx, y, bm, dw, dh, color);
      cx += step;
    }
  } else if (size <= 3) {
    int gap = size <= 2 ? 2 : 3;
    drawSmallText7seg(c, s, x, y, gap, color);
  } else if (size <= 5) {
    drawSmallText7segScaled(c, s, x, y, 2, 3, color);
  } else {
    drawBigText7seg(c, s, x, y, 1, 4, color);
  }
}

static void text7segBounds(const char *s, uint8_t size, uint16_t *w, uint16_t *h) {
  if (!s) { if (w) *w = 0; if (h) *h = 0; return; }
  int n = (int)strlen(s);
  if (n == 0) { if (w) *w = 0; if (h) *h = 0; return; }
  int dw, dh, gap;
  if (size <= 1)        { dw =  8; dh = 12; gap = 1; }
  else if (size <= 3)   { dw = 16; dh = 25; gap = size <= 2 ? 2 : 3; }
  else if (size <= 5)   { dw = 32; dh = 50; gap = 3; }
  else                  { dw = 33; dh = 53; gap = 4; }
  if (w) *w = (uint16_t)(n * (dw + gap) - gap);
  if (h) *h = (uint16_t)dh;
}

// Draw an orthographic Earth globe centered on (cx,cy), radius R, geographically
// centered on (centerLat, centerLon) [radians]. Shades day/night terminator from
// sun declination `dec` [rad] and subsolar longitude `subLon` [rad]. The user's
// position is at the globe center (centered projection), drawn as a dot.
// ponytail: per-pixel inverse orthographic + zenith test on ~pi*R^2 pixels.
// At R=45 that's ~6360 px, each doing ~4 sin/cos + 1 atan2 + 1 asin in float.
// ESP32 handles it in a few ms per frame. Ceiling: animating every frame or
// enlarging R past ~120 would warrant a precomputed lat/lon LUT per radius.
// Twilight band: |cosZ| < TWILIGHT -> blend toward a dimmer shade for a soft
// terminator instead of a hard 1-px edge. Cheap 3-step, no per-channel lerp.
static void drawEarthGlobe(GFXcanvas16 *c, int16_t cx, int16_t cy, int16_t R,
                           double centerLat, double centerLon,
                           double dec, double subLon, uint16_t dotColor) {
  const double sinCL = sin(centerLat), cosCL = cos(centerLat);
  const double sinD  = sin(dec),       cosD  = cos(dec);
  // RGB565 palette — black & white like the old moon.
  //   Day:   sea = white, land = black
  //   Night: sea = dark gray, land = black   (hard terminator, no band)
  const uint16_t SEA_DAY   = 0xFFFF; // white
  const uint16_t SEA_NIGHT = 0x4208; // dark gray
  const uint16_t LAND_DAY  = 0x0000; // black
  const uint16_t LAND_NIGHT= 0x0000; // black
  const uint16_t RIM       = 0x8410; // dim gray outline

  int32_t R2 = (int32_t)R * R;
  for (int16_t dy = -R; dy <= R; dy++) {
    int16_t py = cy + dy;
    if (py < 0 || py >= c->height()) continue;
    int16_t xspan = (int16_t)sqrtf((float)(R2 - (int32_t)dy * dy));
    for (int16_t dx = -xspan; dx <= xspan; dx++) {
      int16_t px = cx + dx;
      if (px < 0 || px >= c->width()) continue;
      double lat, lon;
      float rho = sqrtf((float)(dx * dx + dy * dy));
      if (rho < 0.5f) {
        lat = centerLat; lon = centerLon;
      } else {
        // screen y is down; geographic lat is up -> use -dy for north.
        double c_ang = asin((double)rho / R);
        double sc = sin(c_ang), cc = cos(c_ang);
        double ux =  dx / rho, uy = -dy / rho; // unit screen vector (east, north)
        lat = asin(cc * sinCL + uy * sc * cosCL);
        lon = centerLon + atan2(ux * sc, cc * cosCL - uy * sc * sinCL);
      }
      bool land = earthIsLand(lat * 180.0 / M_PI, lon * 180.0 / M_PI);
      double cosZ = sin(lat) * sinD + cos(lat) * cosD * cos(lon - subLon);
      uint16_t col = (cosZ > 0.0) ? (land ? LAND_DAY : SEA_DAY)
                                  : (land ? LAND_NIGHT : SEA_NIGHT);
      c->drawPixel(px, py, col);
    }
  }
  c->drawCircle(cx, cy, R, RIM);
  // User position is the projection center -> dot at disc center.
  c->fillCircle(cx, cy, 2, dotColor);
}

void DisplayManager::initDisplay() {
  display.begin();
  display.setRotation(1);     // Landscape
  display.fillScreen(0x0000); // Clear initial screen

  // Allocate framebuffer in PSRAM if possible, otherwise heap
  // 536 * 240 * 2 = 257,280 bytes
  canvas = new GFXcanvas16(display.width(), display.height());
  if (canvas) {
    Serial.println("Canvas allocated successfully");
  } else {
    Serial.println("Canvas allocation FAILED!");
  }
}

void DisplayManager::pushToDisplay() {
  if (canvas) {
    lcd_PushColors(0, 0, canvas->width(), canvas->height(),
                   canvas->getBuffer());
  }
}

void DisplayManager::clearDisplay() {
  if (canvas)
    canvas->fillScreen(0x0000);
  pushToDisplay();
}

void DisplayManager::drawText(const String &text, int x, int y) {
  if (!canvas)
    return;
  canvas->fillScreen(0x0000);
  drawText7seg(canvas, text.c_str(), x, y, 3, 0xFFFF); // white, size 3
  pushToDisplay();
}

// ISO 8601 week number from a filled struct tm.
// ponytail: Thursday-of-week method — the ISO week belongs to the year of its
// Thursday, so we compute the Thursday's day-of-year and divide by 7. Edge cases
// (Thursday in prev/next year) resolve to that year's last/first week. The
// prev-year fallback computes Jan 1 weekday to distinguish 52 vs 53.
static int isoWeek(const struct tm &t) {
  int isoWday = (t.tm_wday == 0) ? 7 : t.tm_wday; // Mon=1..Sun=7
  int doy = t.tm_yday + 1;                        // 1-based day of year
  int thuDoy = doy + (4 - isoWday);               // Thursday of this ISO week
  int y = t.tm_year + 1900;
  auto leap = [](int yr) { return (yr%4==0 && yr%100!=0) || (yr%400==0); };
  int yearLen = 365 + (leap(y) ? 1 : 0);
  if (thuDoy < 1) {
    int py = y - 1;
    int jan1Wday = ((isoWday - (doy - 1) - 1) % 7 + 7) % 7 + 1;
    int prevLen = 365 + (leap(py) ? 1 : 0);
    int prevJan1Wday = ((jan1Wday - (prevLen % 7) - 1) % 7 + 7) % 7 + 1;
    bool has53 = (prevJan1Wday == 4) || (leap(py) && prevJan1Wday == 3);
    return has53 ? 53 : 52;
  }
  if (thuDoy > yearLen) return 1;
  return (thuDoy - 1) / 7 + 1;
}

void DisplayManager::drawWatchFace(const String &timeStr) {
  if (!canvas)
    return;

  // ----- Starfield watch face (adapted from watchy-starfield-main) -----
  // Layout (536x240 landscape):
  //   Left two-thirds (0-360), split horizontally:
  //     Top half  (0-120):   Big 7-seg clock, scaled to fill
  //     Bottom half (120-240): Date (DOW + W## on left, DD.MM / YYYY on right)
  //   Right third (360-536): Earth globe (day/night + position dot), wifi, temp
//   Day progress bar: under the clock (24h, hatched sleeping edges + now marker)
  //   Battery icon (32x32): top-right corner, left of the globe

  canvas->fillScreen(0x0000); // black background
  drawStarfield(canvas, 60);   // deterministic procedural stars

  // Fetch local time once for all date/Earth/sun calculations below.
  struct tm timeinfo;
  bool haveTime = getLocalTime(&timeinfo, 10);

  // --- Parse time string "HH:MM:SS" ---
  int hh = timeStr.substring(0, 2).toInt();
  int mm = timeStr.substring(3, 5).toInt();

  // --- Top section: big scaled 7-seg clock ---
  // Digit native 33x53. Scale 2 → 66x106. Top section ~120px tall, fits.
  // 4 digits + colon + gaps. Width = 4*66 + colon(16) + 2*gap(12) = 304.
  const uint16_t TIME_COLOR = 0x07FF; // cyan
  const int SCALE = 2;
  const int DW = 33 * SCALE;  // 66
  const int DH = 53 * SCALE;  // 106
  const int DGAP = 12;
  const int COLON_W = 16;
  int clockW = 4 * DW + COLON_W + 2 * DGAP;  // 304
  const int16_t leftSpan = 360;
  int16_t timeX = (leftSpan - clockW) / 2;     // centered in left 2/3
  int16_t timeY = (120 - DH) / 2;             // centered in top half
  if (timeY < 2) timeY = 2;

  // HH
  drawBigDigitsScaled(canvas, hh, 2, timeX, timeY, SCALE, DGAP, TIME_COLOR);
  // Colon (two dots) between HH and MM
  int16_t colonX = timeX + 2 * DW + DGAP + COLON_W / 2;
  int16_t colonY = timeY + DH / 2;
  canvas->fillCircle(colonX, colonY - 10, 4, TIME_COLOR);
  canvas->fillCircle(colonX, colonY + 10, 4, TIME_COLOR);
  // MM
  drawBigDigitsScaled(canvas, mm, 2, timeX + 2 * DW + DGAP + COLON_W + DGAP,
                      timeY, SCALE, DGAP, TIME_COLOR);

  // --- Bottom section: date ---
  // Layout: [DOW]  [DD.MM]   (DOW on left, date on right, two rows)
  //                [YYYY]
  // DOW sized to match the date block height (~54px → dot size 7 = 56px).
  // Group pushed to the lower-left corner of the screen.
  const uint16_t DATE_COLOR = 0xBDF7; // light blue-white
  const uint16_t LABEL_COLOR = 0x7BEF; // gray

  String dateStr = TimeManager::getCurrentDate(); // "Mon 25/12"

  // Parse day and month from "Mon 25/12"
  int dayNum = 0, monthNum = 0;
  int slashIdx = dateStr.indexOf('/');
  if (slashIdx > 0) {
    int spaceIdx = dateStr.indexOf(' ');
    if (spaceIdx >= 0) {
      dayNum = dateStr.substring(spaceIdx + 1, slashIdx).toInt();
      monthNum = dateStr.substring(slashIdx + 1).toInt();
    }
  }
  int year = haveTime ? timeinfo.tm_year + 1900 : 2025;

  // Measure both blocks.
  const int SDW = 16, SDH = 25, SGAP = 3, DOTW = 6, DDOT_GAP = 4;
  int dateRowW = 2 * (SDW + 3) + DOTW + 2 * (SDW + 3); // DD . MM
  int yearW = 4 * SDW + 3 * SGAP;
  int dateBlockW = (dateRowW > yearW) ? dateRowW : yearW;
  int dateBlockH = SDH + 4 + SDH; // two rows of 25px + 4px gap = 54

  // DOW dot text at size 3 → 8*3 = 24px tall, matches the top row (25px).
  // Bottom row of the DOW column shows "W" + ISO week number.
  const uint8_t DOW_SIZE = 3;
  uint16_t dowW = 0, dowH = 0;
  String dow;
  if (dateStr.length() >= 3) {
    dow = dateStr.substring(0, 3); // "Mon"
    text7segBounds(dow.c_str(), DOW_SIZE, &dowW, &dowH);
  }

  const int COL_GAP = 16;
  int groupW = dowW + COL_GAP + dateBlockW;
  // Push to lower-left: 8px left margin, 8px bottom margin.
  int16_t groupX = 8;
  int16_t groupY = canvas->height() - dateBlockH - 8;
  if (groupY < 122) groupY = 122; // don't cross into top section

  // DOW in the top row (aligned with DD.MM), W## in the bottom row (aligned with YYYY)
  // ponytail: DOW, "W", and week number in gray (LABEL_COLOR) to de-emphasize vs date.
  int16_t dowY = groupY + (SDH - dowH) / 2; // vertically centered in top row
  if (dow.length()) {
    drawText7seg(canvas, dow.c_str(), groupX, dowY, DOW_SIZE, LABEL_COLOR);
  }

  // Week number in the bottom row of the DOW column
  int16_t weekY = groupY + SDH + 4; // same baseline as YYYY row
  drawText7seg(canvas, "W", groupX, weekY + (SDH - 24) / 2, DOW_SIZE, LABEL_COLOR);
  if (haveTime) {
    int wk = isoWeek(timeinfo);
    drawSmallDigits(canvas, wk, 2, groupX + 6 * DOW_SIZE + 2, weekY, LABEL_COLOR);
  } else {
    drawSmallDigits(canvas, 0, 2, groupX + 6 * DOW_SIZE + 2, weekY, LABEL_COLOR);
  }

  // Date block on the right of DOW
  int16_t dbX = groupX + dowW + COL_GAP;
  int16_t dbY = groupY;

  // Row 1: DD . MM
  if (dayNum > 0) {
    int16_t dx = dbX + (dateBlockW - dateRowW) / 2;
    drawSmallDigits(canvas, dayNum, 2, dx, dbY, DATE_COLOR);
    int16_t dotX = dx + 2 * (SDW + 3) + DDOT_GAP / 2;
    canvas->fillCircle(dotX, dbY + SDH / 2 - 3, 2, DATE_COLOR);
    canvas->fillCircle(dotX, dbY + SDH / 2 + 3, 2, DATE_COLOR);
    drawSmallDigits(canvas, monthNum, 2,
                    dx + 2 * (SDW + 3) + DOTW + DDOT_GAP, dbY, DATE_COLOR);
  }

  // Row 2: YYYY
  int16_t yx = dbX + (dateBlockW - yearW) / 2;
  drawSmallDigits(canvas, year, 4, yx, dbY + SDH + 4, DATE_COLOR);

  // --- Top-right corner: wifi icon + battery icon ---
  // Wifi (25x18 → 31x23) and battery (32x32 → 40x40), both in white.
  bool wifiOn = (WiFi.status() == WL_CONNECTED);
  int batPct = BatteryManager::getPercentage();
  uint8_t batIw = 0, batIh = 0;
  // ponytail: charging == USB cable plugged (VBUS present), detected via the
  // ESP32-S3 USB-Serial-JTAG peripheral. Ceiling: reads "charging" whenever
  // USB is connected even if no power flows (e.g. a PC port); a dumb charger
  // without the USB handshake may not register. Upgrade: wire a GPIO to VBUS.
  bool charging = HWCDCSerial.isPlugged();
  const unsigned char *batIcon = charging
      ? (batIw = 32, batIh = 32, BATICON_BATTERY_CHARGING)
      : batteryIconBitmap(batPct, &batIw, &batIh);
  const uint16_t ICON_COLOR = 0xFFFF; // white
  const int16_t topRightMargin = 4;
  // Battery: native 32x32 → target 40x40
  const int16_t BAT_TW = 40, BAT_TH = 40;
  float batSx = (float)BAT_TW / batIw;
  float batSy = (float)BAT_TH / batIh;
  int16_t batX = canvas->width() - BAT_TW - topRightMargin;
  int16_t topIconY = topRightMargin;
  if (batIcon) {
    drawBitmapScaled(canvas, batX, topIconY, batIcon, batIw, batIh,
                     batSx, batSy, ICON_COLOR);
  }
  // Wifi icon to the left of the battery, vertically centered with it.
  // Native 25x18 → target 31x23
  const int WIFI_W = 25, WIFI_H = 18;
  const int16_t WIFI_TW = 31, WIFI_TH = 23;
  float wifiSx = (float)WIFI_TW / WIFI_W;
  float wifiSy = (float)WIFI_TH / WIFI_H;
  int16_t wifiX = batX - WIFI_TW - 6;
  int16_t wifiY = topIconY + (BAT_TH - WIFI_TH) / 2;
  drawBitmapScaled(canvas, wifiX, wifiY, wifiOn ? wifi : wifioff,
                   WIFI_W, WIFI_H, wifiSx, wifiSy, ICON_COLOR);

  // --- Right column: Earth globe + sunrise/sunset + temp ---
  // Orthographic globe 91x91 (R=45), centered geographically on the user's
  // location so the user's face of Earth (Europe, for Copenhagen) is shown
  // and the position dot sits at the disc center. x=414, ends at 505.
  // SR/SS times are stacked vertically in the dead space between clock
  // (ends ~332) and globe (starts 414), below the globe's vertical extent.
  const int16_t rightX = 414;
  const int GLOBE_SIZE = 91;
  const int GLOBE_R = GLOBE_SIZE / 2;          // 45
  const int16_t globeY = 56;
  const int16_t globeX = rightX;
  const int16_t globeCx = globeX + GLOBE_R;
  const int16_t globeCy = globeY + GLOBE_R;

  // User location + UTC offset (shared by the globe terminator and Dusk2Dawn).
  float lat = String(LATITUDE).toFloat();
  float lon = String(LONGITUDE).toFloat();
  float tzOffset = 0;
  if (haveTime) {
    time_t now = mktime(&timeinfo);
    struct tm utc;
    gmtime_r(&now, &utc);
    tzOffset = (float)(timeinfo.tm_hour - utc.tm_hour) +
               (float)(timeinfo.tm_min - utc.tm_min) / 60.0f;
    if (tzOffset > 12)  tzOffset -= 24;
    if (tzOffset < -12) tzOffset += 24;
  }

  // Sun geometry for the day/night terminator.
  // ponytail: declination from the standard day-of-year approximation
  // (good to ~0.5 deg); subsolar longitude from UTC hours ignoring the
  // equation of time (good to ~0.5 deg). Both well within a 91px globe.
  //   dec       = -23.44 deg * cos(2pi/365 * (N+10))   N = day of year
  //   subLon    = (12 - utcHours) * 15 deg             utcHours = local - tz
  {
    int doy = haveTime ? timeinfo.tm_yday + 1 : 1;        // 1..365
    double decDeg = -23.44 * cos(2.0 * M_PI / 365.0 * (doy + 10));
    double utcHours = haveTime
      ? (timeinfo.tm_hour + timeinfo.tm_min / 60.0 - tzOffset)
      : 12.0;
    double subLonDeg = (12.0 - utcHours) * 15.0;
    while (subLonDeg >  180.0) subLonDeg -= 360.0;
    while (subLonDeg < -180.0) subLonDeg += 360.0;
    drawEarthGlobe(canvas, globeCx, globeCy, GLOBE_R,
                   lat * M_PI / 180.0, lon * M_PI / 180.0,
                   decDeg * M_PI / 180.0, subLonDeg * M_PI / 180.0,
                   0xF800); // red position dot
  }

  // Sunrise/sunset via Dusk2Dawn
  Dusk2Dawn d2d(lat, lon, tzOffset);
  int sr = -1, ss = -1;
  if (haveTime) {
    sr = d2d.sunrise(timeinfo.tm_year + 1900, timeinfo.tm_mon + 1,
                     timeinfo.tm_mday, false);
    ss = d2d.sunset(timeinfo.tm_year + 1900, timeinfo.tm_mon + 1,
                    timeinfo.tm_mday, false);
  }

  const uint16_t SUN_COLOR = 0xFD20; // orange
  const uint16_t SUN_LABEL_COLOR = 0xBDF7; // light blue-white

  // SR/SS times: inline (label next to time), stacked vertically at the
  // left, aligned with the date group rows. Frees vertical space under the
  // clock for the day bar to sit lower.
  if (sr >= 0 && ss >= 0) {
    int srH = sr / 60, srM = sr % 60;
    int ssH = ss / 60, ssM = ss % 60;

    const int16_t ssX = 170;      // right of date group (ends ~160)
    const int16_t labelW = 35;    // "SR"/"SS" at size 3 (16x25, gap 3)
    const int16_t labelGap = 4;
    const int16_t digitX = ssX + labelW + labelGap;
    const int16_t srY = 178;      // aligned with date group top row
    const int16_t ssY = 178 + 25 + 4; // aligned with date group bottom row
    const int16_t labelYOff = 0;  // size-3 label is 25px, same as row

    // SR
    drawText7seg(canvas, "SR", ssX, srY + labelYOff, 3, LABEL_COLOR);
    drawSmallDigits(canvas, srH, 2, digitX, srY, SUN_LABEL_COLOR);
    int16_t srColonX = digitX + 2 * (16 + 3);
    canvas->fillCircle(srColonX, srY + 8, 2, SUN_LABEL_COLOR);
    canvas->fillCircle(srColonX, srY + 16, 2, SUN_LABEL_COLOR);
    drawSmallDigits(canvas, srM, 2, srColonX + 4, srY, SUN_LABEL_COLOR);

    // SS
    drawText7seg(canvas, "SS", ssX, ssY + labelYOff, 3, LABEL_COLOR);
    drawSmallDigits(canvas, ssH, 2, digitX, ssY, SUN_LABEL_COLOR);
    int16_t ssColonX = digitX + 2 * (16 + 3);
    canvas->fillCircle(ssColonX, ssY + 8, 2, SUN_LABEL_COLOR);
    canvas->fillCircle(ssColonX, ssY + 16, 2, SUN_LABEL_COLOR);
    drawSmallDigits(canvas, ssM, 2, ssColonX + 4, ssY, SUN_LABEL_COLOR);
  } else {
    drawText7seg(canvas, "Sun: N/A", 170, 190, 1, LABEL_COLOR);
  }

  // --- Day progress bar under the clock ---
  // Full 24h (midnight→midnight). Hatched edges = sleeping (night: 0→sunrise,
  // sunset→1440). Clear middle = awake (sunrise→sunset). Triangle = now.
  // ponytail: hatch is a fixed 3px-pitch diagonal scan; ceiling = barH>~20px
  // would leave gaps — upgrade to a tiled PROGMEM pattern if enlarged.
  if (sr >= 0 && ss >= 0) {
    const int16_t barX = timeX;
    const int16_t barY = 148;
    const int16_t barW = clockW;
    const int16_t barH = 12;
    const uint16_t HATCH_COLOR = 0x4208; // dim blue-gray, sleepy

    // Hatched sleeping edges first, then border on top.
    int16_t srX = barX + (int32_t)sr * barW / 1440;
    int16_t ssX = barX + (int32_t)ss * barW / 1440;
    for (int16_t hx = barX + 1; hx < barX + barW - 1; hx += 3) {
      if (hx >= srX && hx < ssX) continue; // skip awake middle
      int16_t top = barY + 1, bot = barY + barH - 2;
      int16_t ex = hx + 2;
      if (ex > barX + barW - 2) ex = barX + barW - 2;
      canvas->drawLine(hx, bot, ex, top, HATCH_COLOR);
    }
    canvas->drawRect(barX, barY, barW, barH, LABEL_COLOR);

    // Triangle marker (current time) above the bar, pointing down.
    int nowMin = timeinfo.tm_hour * 60 + timeinfo.tm_min;
    int16_t mx = barX + (int32_t)nowMin * barW / 1440;
    if (mx < barX + 4) mx = barX + 4;
    if (mx > barX + barW - 4) mx = barX + barW - 4;
    canvas->fillTriangle(mx, barY, mx - 4, barY - 6, mx + 4, barY - 6, SUN_COLOR);
  }

  // Temperature (yellow, right column, aligned vertically with SS time)
  const uint16_t TEMP_COLOR = 0xFFE0;
  String tempStr = WeatherManager::getTemperature();
  bool tempValid = tempStr.length() > 0 && isDigit(tempStr.charAt(0));
  if (tempValid) {
    drawText7seg(canvas, "T:", rightX, 212, 2, LABEL_COLOR);
    int dotPos = tempStr.indexOf('.');
    int tempInt = (dotPos > 0) ? tempStr.substring(0, dotPos).toInt()
                                : tempStr.toInt();
    if (tempInt < 0) {
      drawText7seg(canvas, "-", rightX + 24, 212, 2, TEMP_COLOR);
      drawSmallDigits(canvas, -tempInt, 2, rightX + 44, 212, TEMP_COLOR);
    } else {
      drawSmallDigits(canvas, tempInt, 2, rightX + 24, 212, TEMP_COLOR);
    }
    drawText7seg(canvas, "C", rightX + 2 * (16 + 3) + 44, 212, 2, TEMP_COLOR);
  } else {
    drawText7seg(canvas, "T:--", rightX, 212, 2, LABEL_COLOR);
  }

  // --- Corner brackets around each section ---
  const uint16_t BRACKET_COLOR = LABEL_COLOR; // gray
  const uint8_t BRACKET_LEG = 8;
  // Time (top-left, scaled clock)
  drawCornerBrackets(canvas, timeX - 4, timeY - 4,
                     clockW + 8, DH + 8, BRACKET_LEG, BRACKET_COLOR);
  // Calendar (lower-left, DOW + date block)
  drawCornerBrackets(canvas, groupX - 4, groupY - 4,
                     groupW + 8, dateBlockH + 8, BRACKET_LEG, BRACKET_COLOR);
  // Earth globe (right, 91x91)
  drawCornerBrackets(canvas, globeX - 4, globeY - 4,
                     GLOBE_SIZE + 8, GLOBE_SIZE + 8, BRACKET_LEG, BRACKET_COLOR);
  // SR/SS inline times (left, aligned with date group rows)
  drawCornerBrackets(canvas, 166, 174, 121, 62, BRACKET_LEG, BRACKET_COLOR);
  // Temperature (right column, aligned with SS time)
  drawCornerBrackets(canvas, rightX - 4, 208, 84, 32, BRACKET_LEG,
                     BRACKET_COLOR);

  // Push buffer to display
  pushToDisplay();
}

void DisplayManager::drawWeatherScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Display is 536 wide x 240 tall (landscape).
  // Layout:
  //   0-30:    Title + current temp + weather icon
  //  35-165:   Graph area (temperature line + precipitation fill)
  // 170-178:   Hour labels under graph
  // 185-235:   Legend + min/max + location (single row, 536px wide)

  // --- Title ---
  drawText7seg(canvas, "WEATHER", 10, 5, 3, 0xFFE0); // yellow, size 3

  if (!WeatherManager::hasHourlyData()) {
    drawText7seg(canvas, "Fetching forecast...", 10, 40, 2, 0x7BEF);
    drawText7seg(canvas, "Updates every 10 min", 10, 65, 1, 0x7BEF);
    pushToDisplay();
    return;
  }

  const HourlyForecast &fc = WeatherManager::getHourlyForecast();
  uint8_t n = fc.count;
  if (n == 0) {
    drawText7seg(canvas, "No data", 10, 40, 2, 0xF800);
    pushToDisplay();
    return;
  }

  // --- Current weather icon (top-right) ---
  uint8_t iw = 0, ih = 0;
  const unsigned char *icon = weatherIconBitmap(fc.weatherCode[0], &iw, &ih);
  if (icon) {
    canvas->drawBitmap(canvas->width() - iw - 10, 5, icon, iw, ih, 0xFFFF);
  }

  // --- Current temperature text (below title) ---
  String currTemp = String((int)round(fc.temperature[0]));
  drawText7seg(canvas, (currTemp + "C").c_str(), 140, 12, 2, 0xFFFF); // white, size 2

  // --- Graph area ---
  // ponytail: graph leaves 34px on the left for the temperature ruler labels.
  // Temperature is a red line, precipitation is a light-blue filled area.
  // Both share the same x-axis (hours). Y-axes are independent.
  const int16_t rulerW = 24;
  const int16_t graphX = 10 + rulerW;           // 34
  const int16_t graphW = canvas->width() - 20 - rulerW;  // 492px
  const int16_t graphY = 35;
  const int16_t graphH = 160;
  const int16_t graphBottom = graphY + graphH;  // 195

  // Guard against single data point (division by zero in x mapping)
  if (n < 2) {
    int16_t x = graphX + graphW / 2;
    int16_t y = graphY + graphH / 2;
    canvas->fillCircle(x, y, 3, 0xF800);
    pushToDisplay();
    return;
  }

  // Find min/max for temperature scaling
  float tempMin = fc.temperature[0], tempMax = fc.temperature[0];
  float precipMax = 0.0f;
  for (uint8_t i = 0; i < n; i++) {
    if (fc.temperature[i] < tempMin) tempMin = fc.temperature[i];
    if (fc.temperature[i] > tempMax) tempMax = fc.temperature[i];
    if (fc.precipitation[i] > precipMax) precipMax = fc.precipitation[i];
  }
  // Snap to integer bounds so ruler ticks align exactly with the temperature
  // line. Floor the min, ceil the max, then pad by 1 degree so the line
  // doesn't touch the graph edges.
  tempMin = floorf(tempMin);
  tempMax = ceilf(tempMax);
  if (tempMax - tempMin < 2.0f) { tempMin -= 1.0f; tempMax += 1.0f; }
  tempMin -= 1.0f;
  tempMax += 1.0f;
  if (precipMax < 0.1f) precipMax = 1.0f; // avoid div-by-zero, show flat baseline

  // --- Precipitation area (light blue fill) ---
  // ponytail: filled area chart using vertical strips per data point.
  // RGB565 light blue: 0x4B5F (approx #29B5FE)
  const uint16_t PRECIP_COLOR = 0x4B5F;

  for (uint8_t i = 0; i < n; i++) {
    int16_t x = graphX + (int16_t)(graphW * i) / (n - 1);
    int16_t xNext = (i + 1 < n) ? graphX + (int16_t)(graphW * (i + 1)) / (n - 1) : x + 1;

    float precipH = (fc.precipitation[i] / precipMax) * (graphH * 0.5f);
    int16_t barH = (int16_t)precipH;

    // Draw filled bar from bottom up
    if (barH > 0) {
      canvas->fillRect(x, graphBottom - barH, xNext - x, barH, PRECIP_COLOR);
    }
  }

  // --- Temperature line (red) ---
  // ponytail: connected line graph. RGB565 red: 0xF800
  const uint16_t TEMP_COLOR = 0xF800;

  auto tempY = [&](float t) -> int16_t {
    float frac = (t - tempMin) / (tempMax - tempMin);
    return graphBottom - (int16_t)(frac * graphH);
  };

  for (uint8_t i = 1; i < n; i++) {
    int16_t x0 = graphX + (int16_t)(graphW * (i - 1)) / (n - 1);
    int16_t y0 = tempY(fc.temperature[i - 1]);
    int16_t x1 = graphX + (int16_t)(graphW * i) / (n - 1);
    int16_t y1 = tempY(fc.temperature[i]);
    canvas->drawLine(x0, y0, x1, y1, TEMP_COLOR);
  }

  // Draw data points as small circles
  for (uint8_t i = 0; i < n; i++) {
    int16_t x = graphX + (int16_t)(graphW * i) / (n - 1);
    int16_t y = tempY(fc.temperature[i]);
    canvas->fillCircle(x, y, 2, TEMP_COLOR);
  }

  // --- Peak / Low / Average temperature annotations ---
  // ponytail: peak label sits below the point, low label above, average at the
  // hour whose temp is closest to the mean. Size-1 text (8x12) keeps it compact.
  // Ceiling: labels can collide on tight clusters or at graph edges; no overlap
  // avoidance. Upgrade: shift label x by text width when near right edge.
  uint8_t peakIdx = 0, lowIdx = 0;
  float sum = 0.0f;
  for (uint8_t i = 0; i < n; i++) {
    if (fc.temperature[i] > fc.temperature[peakIdx]) peakIdx = i;
    if (fc.temperature[i] < fc.temperature[lowIdx])  lowIdx  = i;
    sum += fc.temperature[i];
  }
  float avg = sum / n;
  uint8_t avgIdx = 0;
  float bestDiff = fabsf(fc.temperature[0] - avg);
  for (uint8_t i = 1; i < n; i++) {
    float d = fabsf(fc.temperature[i] - avg);
    if (d < bestDiff) { bestDiff = d; avgIdx = i; }
  }

  const uint16_t PEAK_COLOR = 0xFFE0; // yellow
  const uint16_t LOW_COLOR  = 0x07FF; // cyan
  const uint16_t AVG_COLOR  = 0x07E0; // green
  const int16_t lblH = 12;            // size-1 text height
  const int16_t lblW = 8;             // size-1 char width (approx, per digit)

  auto drawTempLabel = [&](uint8_t idx, int16_t yOff, uint16_t color) {
    int16_t x = graphX + (int16_t)(graphW * idx) / (n - 1);
    int16_t y = tempY(fc.temperature[idx]) + yOff;
    char buf[8];
    snprintf(buf, sizeof(buf), "%d", (int)round(fc.temperature[idx]));
    // Center the label horizontally on the point
    int16_t textW = (int16_t)(strlen(buf) * (lblW + 1));
    int16_t lx = x - textW / 2;
    // Clamp inside graph area
    if (lx < graphX) lx = graphX;
    if (lx + textW > graphX + graphW) lx = graphX + graphW - textW;
    drawText7seg(canvas, buf, lx, y, 1, color);
  };

  drawTempLabel(peakIdx,  4,           PEAK_COLOR); // below peak
  drawTempLabel(lowIdx,  -(lblH + 2),  LOW_COLOR);  // above low
  // Average: label sits at the avg temp's y (middle of the temp band) at the
  // hour where the curve is closest to the average.
  {
    int16_t ax = graphX + (int16_t)(graphW * avgIdx) / (n - 1);
    int16_t ay = tempY(avg) - lblH / 2;
    char buf[8];
    snprintf(buf, sizeof(buf), "%d", (int)round(avg));
    int16_t textW = (int16_t)(strlen(buf) * (lblW + 1));
    int16_t lx = ax - textW / 2;
    if (lx < graphX) lx = graphX;
    if (lx + textW > graphX + graphW) lx = graphX + graphW - textW;
    drawText7seg(canvas, buf, lx, ay, 1, AVG_COLOR);
  }

  // --- Graph border ---
  canvas->drawRect(graphX, graphY, graphW, graphH, 0x4208); // dark gray border

  // --- Temperature ruler (left side) ---
  // ponytail: 3 tick marks + labels (max, mid, min) aligned to the graph's y-scale.
  // Shows the actual temp range so you can read values off the red line.
  const uint16_t RULER_COLOR = 0x8410; // dark gray
  int tempHi = (int)tempMax; // already integer-bounded + padded
  int tempLo = (int)tempMin;
  int tempMid = (tempHi + tempLo) / 2;

  struct { int16_t y; int val; } ticks[] = {
    { graphY,              tempHi },
    { graphY + graphH / 2, tempMid },
    { graphBottom,        tempLo },
  };
  for (auto &t : ticks) {
    // tick mark on the left edge of the graph
    canvas->drawLine(graphX - 4, t.y, graphX, t.y, RULER_COLOR);
    // label just left of the tick
    char buf[8];
    snprintf(buf, sizeof(buf), "%d", t.val);
    drawText7seg(canvas, buf, graphX - 22, t.y - 4, 1, 0x7BEF);
  }

  // --- Hour labels under graph ---
  // ponytail: show every 3rd hour to fit. Size 1 dot text.
  const int16_t labelY = graphBottom + 5;
  for (uint8_t i = 0; i < n; i += 3) {
    int16_t x = graphX + (int16_t)(graphW * i) / (n - 1);
    char buf[8];
    snprintf(buf, sizeof(buf), "%02d", fc.hour[i]);
    // Center the 2-char label on the data point
    drawText7seg(canvas, buf, x - 6, labelY, 1, 0x7BEF); // gray, size 1
  }

  // --- Legend + location (single row at y=218) ---
  const int16_t legendY = 218;
  // Precipitation swatch
  canvas->fillRect(10, legendY, 12, 12, PRECIP_COLOR);
  drawText7seg(canvas, "Rain", 28, legendY - 2, 1, 0x7BEF);

  // Temperature swatch (line)
  canvas->drawLine(90, legendY + 6, 102, legendY + 6, TEMP_COLOR);
  canvas->fillCircle(96, legendY + 6, 2, TEMP_COLOR);
  drawText7seg(canvas, "Temp", 108, legendY - 2, 1, 0x7BEF);

  // --- Location (right-aligned) ---
  drawText7seg(canvas, "Copenhagen", canvas->width() - 90, legendY - 2, 1, 0x7BEF);

  pushToDisplay();
}

void DisplayManager::drawAlarmsScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  drawText7seg(canvas, "ALARMS", 10, 10, 3, 0xF81F); // magenta, size 3

  // Alarm info
  drawText7seg(canvas, "Alarm 1: --:--", 10, 50, 2, 0xFFFF); // white
  drawText7seg(canvas, "Status: Inactive", 10, 80, 2, 0xFFFF);

  // Note
  drawText7seg(canvas, "Use app to set alarms", 10, 120, 1, 0x7BEF); // gray

  pushToDisplay();
}

void DisplayManager::drawBatteryScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  drawText7seg(canvas, "BATTERY", 10, 10, 3, 0x07E0); // green, size 3

  // Get battery data
  float batVolt = BatteryManager::getVoltage();
  int batPct = BatteryManager::getPercentage();

  // Voltage
  drawText7seg(canvas, ("Voltage: " + String(batVolt, 2) + "V").c_str(), 10, 50, 2,
          0xFFFF); // white

  // Percentage
  drawText7seg(canvas, ("Charge: " + String(batPct) + "%").c_str(), 10, 80, 2,
          0xFFFF);

  // Large battery bar visualization
  int barWidth = map(batPct, 0, 100, 0, 200); // max 200 px width
  int barX = 10;
  int barY = 120;

  // Border
  canvas->drawRect(barX - 2, barY - 2, 204, 34, 0xFFFF);

  // Background (dark gray)
  canvas->fillRect(barX, barY, 200, 30, 0x2104);

  // Fill based on percentage
  uint16_t barColor;
  if (batPct > 50) {
    barColor = 0x07E0; // green
  } else if (batPct > 20) {
    barColor = 0xFFE0; // yellow
  } else {
    barColor = 0xF800; // red
  }
  canvas->fillRect(barX, barY, barWidth, 30, barColor);

  // Status text
  drawText7seg(canvas, "GPIO15: Power enabled", 10, 170, 1, 0x7BEF); // gray

  pushToDisplay();
}

void DisplayManager::drawBluetoothScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  drawText7seg(canvas, "BLUETOOTH", 10, 10, 3, 0x001F); // blue, size 3

  // Connection status
  bool connected = BluetoothManager::isConnected();

  // "Status: " in white, then the state word in green/red on the same line.
  drawText7seg(canvas, "Status: ", 10, 50, 2, 0xFFFF); // white
  uint16_t stW, stH;
  text7segBounds("Status: ", 2, &stW, &stH);
  if (connected) {
    drawText7seg(canvas, "Connected", 10 + (int16_t)stW, 50, 2, 0x07E0); // green
  } else {
    drawText7seg(canvas, "Disconnected", 10 + (int16_t)stW, 50, 2, 0xF800); // red
  }

  // Device Name
  drawText7seg(canvas, "Device: Lilygo_Watch", 10, 80, 2, 0xFFFF); // white

  // Notifications
  drawText7seg(canvas, "Last Message:", 10, 110, 2, 0xFFFF);
  String note = BluetoothManager::getNotification();
  if (note.length() > 0) {
    drawText7seg(canvas, note.c_str(), 10, 140, 1, 0xFFFF);
  } else {
    drawText7seg(canvas, "No new messages", 10, 140, 1, 0xFFFF);
  }

  // Instructions
  if (!connected) {
    drawText7seg(canvas, "Pair with 'Lilygo_Watch'", 10, 170, 1, 0x7BEF); // gray
    drawText7seg(canvas, "Use Serial Bluetooth Terminal", 10, 185, 1, 0x7BEF);
  }

  pushToDisplay();
}

// ponytail: crude RGB565 channel-wise lerp. Not gamma-correct, but you can't
// tell the difference on a 1.91" AMOLED during a 200ms animation.
static uint16_t lerp565(uint16_t a, uint16_t b, float t) {
  int ra = (a >> 11) & 0x1F, ga = (a >> 5) & 0x3F, ba = a & 0x1F;
  int rb = (b >> 11) & 0x1F, gb = (b >> 5) & 0x3F, bb = b & 0x1F;
  int r  = ra + (int)((rb - ra) * t);
  int g  = ga + (int)((gb - ga) * t);
  int bl = ba + (int)((bb - ba) * t);
  return (uint16_t)((r << 11) | (g << 5) | bl);
}

void DisplayManager::drawWifiConnecting() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Pulse: 0..1 oscillation, ~1.9s period
  float phase = sinf(millis() / 300.0f) * 0.5f + 0.5f;
  uint16_t iconColor = lerp565(0x2104, 0x07FF, phase); // dark gray -> bright cyan

  // Centered 48x48 wifi icon, slightly above center to leave room for text
  int16_t iconX = (canvas->width() - 48) / 2;   // 244
  int16_t iconY = (canvas->height() - 48) / 2 - 15; // 81
  canvas->drawBitmap(iconX, iconY, ICON_WIFI_48, 48, 48, iconColor);

  // "Connecting..." text below
  const char *msg = "Connecting...";
  uint16_t w, h;
  text7segBounds(msg, 2, &w, &h);
  drawText7seg(canvas, msg, (canvas->width() - w) / 2, iconY + 48 + 10, 2,
          0x7BEF); // gray

  pushToDisplay();
}

void DisplayManager::drawConfigMenu(uint8_t selectedIndex) {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  drawText7seg(canvas, "CONFIG", 10, 10, 3, 0xFFE0); // yellow

  const uint8_t count = MenuManager::configItemCount();
  // ponytail: hard-coded vertical list spacing. Works for the current 1–3 items;
  // beyond that the list overflows the 240px height and needs scrolling.
  const int16_t startY = 80;
  const int16_t itemH  = 55;

  for (uint8_t i = 0; i < count; i++) {
    int16_t y = startY + i * itemH;
    const char* label = MenuManager::configItemLabel(i);
    bool sel = (i == selectedIndex);
    uint16_t col = sel ? 0x07FF : 0x7BEF;
    uint16_t bulletCol = sel ? 0x07FF : 0x4208;

    // Bullet
    canvas->fillCircle(15, y + 12, 5, bulletCol);

    // Label
    drawText7seg(canvas, label, 35, y, 3, col);

    // Icon for the Wi-Fi setup item; uses the same Wi-Fi bitmaps as the status screen.
    if (i == 0) {
      uint8_t iw = 0, ih = 0;
      const unsigned char* bm = menuIconBitmap(4, sel ? 48 : 32, &iw, &ih);
      if (bm) {
        int16_t ix = canvas->width() - iw - 10;
        int16_t iy = y + (itemH - ih) / 2;
        canvas->drawBitmap(ix, iy, bm, iw, ih, col);
      }
    }
  }

  pushToDisplay();
}

void DisplayManager::drawWifiPortalScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  const char* title = "WIFI SETUP";
  uint16_t w, h;
  text7segBounds(title, 3, &w, &h);
  drawText7seg(canvas, title, (canvas->width() - w) / 2, 15, 3, 0x07FF); // cyan

  // Wi-Fi icon
  int16_t iconX = (canvas->width() - 48) / 2;
  int16_t iconY = 70;
  canvas->drawBitmap(iconX, iconY, ICON_WIFI_48, 48, 48, 0x07FF);

  // Instructions
  const char* line1 = "Connect to: W5-Setup";
  const char* line2 = "Open 192.168.4.1";
  const char* line3 = "Enter Wi-Fi details";

  text7segBounds(line1, 2, &w, &h);
  drawText7seg(canvas, line1, (canvas->width() - w) / 2, iconY + 48 + 20, 2, 0xFFFF);
  text7segBounds(line2, 2, &w, &h);
  drawText7seg(canvas, line2, (canvas->width() - w) / 2, iconY + 48 + 45, 2, 0xFFFF);
  text7segBounds(line3, 2, &w, &h);
  drawText7seg(canvas, line3, (canvas->width() - w) / 2, iconY + 48 + 70, 2, 0x7BEF);

  pushToDisplay();
}

void DisplayManager::drawWifiResultScreen(bool connected, const String &message) {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  const char* title = "WIFI SETUP";
  uint16_t w, h;
  text7segBounds(title, 3, &w, &h);
  drawText7seg(canvas, title, (canvas->width() - w) / 2, 15, 3, 0x07FF);

  // Status icon
  int16_t iconX = (canvas->width() - 48) / 2;
  int16_t iconY = 60;
  uint16_t iconCol = connected ? 0x07E0 : 0xF800;
  canvas->drawBitmap(iconX, iconY, ICON_WIFI_48, 48, 48, iconCol);

  // Status word
  const char* status = connected ? "Connected" : "Failed";
  text7segBounds(status, 3, &w, &h);
  drawText7seg(canvas, status, (canvas->width() - w) / 2, iconY + 48 + 15, 3,
          iconCol);

  // Message (truncated to screen width)
  String msg = message;
  if (msg.length() > 32) {
    msg = msg.substring(0, 29) + "...";
  }
  text7segBounds(msg.c_str(), 2, &w, &h);
  drawText7seg(canvas, msg.c_str(), (canvas->width() - w) / 2, iconY + 48 + 55, 2,
          0xFFFF);

  pushToDisplay();
}

// ponytail: MM:SS.CC from milliseconds. Caps at 99 minutes; a wrist stopwatch
// session rarely exceeds that. Ceiling: rolls over at 100 min. Upgrade: hours.
static String formatSw(uint32_t ms) {
  uint32_t totalCs = ms / 10;
  uint32_t s = totalCs / 100;
  uint32_t m = s / 60;
  uint32_t cs = totalCs % 100;
  s = s % 60;
  m = m % 100;
  char buf[12];
  snprintf(buf, sizeof(buf), "%02u:%02u.%02u", (unsigned)m, (unsigned)s, (unsigned)cs);
  return String(buf);
}

void DisplayManager::drawStopwatch() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // ----- Status label (top, centered) -----
  const char *status;
  uint16_t statusColor;
  if (StopwatchManager::isRunning()) {
    status = "RUNNING";
    statusColor = 0x07E0; // green
  } else if (StopwatchManager::isStopped()) {
    status = "STOPPED";
    statusColor = 0xF800; // red
  } else {
    status = "READY";
    statusColor = 0x07FF; // cyan
  }

  uint16_t w, h;
  text7segBounds(status, 2, &w, &h);
  drawText7seg(canvas, status, (canvas->width() - w) / 2, 12, 2, statusColor);

  // ----- Big elapsed time (centered, textSize 8) -----
  String timeStr = formatSw(StopwatchManager::getElapsedMs());
  text7segBounds(timeStr.c_str(), 8, &w, &h);
  drawText7seg(canvas, timeStr.c_str(), (canvas->width() - w) / 2,
          (canvas->height() - h) / 2, 8, 0xFFFF); // white

  // ----- Lap line (below time) or controls hint -----
  uint8_t laps = StopwatchManager::getLapCount();
  if (laps > 0) {
    String lapStr = "LAP " + String(laps) + ": " + formatSw(StopwatchManager::getLastLapMs());
    text7segBounds(lapStr.c_str(), 2, &w, &h);
    drawText7seg(canvas, lapStr.c_str(), (canvas->width() - w) / 2, 170, 2,
            0xFFE0); // yellow
  }

  // Controls hint (bottom, tiny gray)
  const char *hint = "TOP:START/STOP  BOT:LAP/RST";
  text7segBounds(hint, 1, &w, &h);
  drawText7seg(canvas, hint, (canvas->width() - w) / 2, 222, 1, 0x7BEF); // gray

  pushToDisplay();
}

// Draw one menu item at a given angle on the arc. closeness (0..1) controls
// visual prominence: 1.0 = selected (large, white, bright dot), 0.0 = tiny, dim, blurred.
static void drawMenuItem(GFXcanvas16 *c, int16_t cx, int16_t cy, int16_t r,
                         float angleDeg, uint8_t labelIdx, float closeness) {
  if (closeness < 0.0f) closeness = 0.0f;
  if (closeness > 1.0f) closeness = 1.0f;

  float a = angleDeg * M_PI / 180.0f;
  int16_t ax = cx + (int16_t)(r * cosf(a));
  int16_t ay = cy + (int16_t)(r * sinf(a));

  // Dot: grows from r=2 (very dim) to r=6 (bright cyan) as it approaches center
  uint16_t dotColor = lerp565(0x2104, 0x07FF, closeness);
  uint8_t  dotRad   = 2 + (uint8_t)(closeness * 4.0f + 0.5f);
  c->fillCircle(ax, ay, dotRad, dotColor);

  String label(MenuManager::menuItemLabel(labelIdx));

  // ponytail: three visual tiers based on closeness to center.
  //   closeness >= 0.6: SELECTED — size 6, white, left-anchored at arc point
  //   closeness >= 0.25: NEAR — size 4, medium gray, left-anchored
  //   closeness < 0.25: FAR — size 2, very dim, simulated blur via 3x offset draw
  // Text is left-anchored at the arc point and extends toward the outer edge
  // (rightward) so the block reads as screen-centered, not arc-centered.
  // The blur is faked by printing the text 3 times with 1px offsets in a dim color.
  // Cheap (3 print calls instead of 1) but reads as "out of focus" on AMOLED.
  bool isSelected = (closeness >= 0.6f);
  bool isFar      = (closeness < 0.25f);

  uint8_t  textSize = isSelected ? 6 : (isFar ? 2 : 4);
  uint16_t textCol  = lerp565(0x4208, 0xFFFF, closeness);  // very dark gray -> white

  uint16_t w, h;
  text7segBounds(label.c_str(), textSize, &w, &h);
  int16_t tx = ax;            // left-anchored at arc point, extends toward outer edge
  int16_t ty = ay - (int16_t)h / 2;

  if (isFar) {
    // ponytail: fake blur — draw 3 copies at 1px offsets in a dimmer color.
    // No real Gaussian blur in Adafruit_GFX; this is the cheapest approximation.
    // Icons skipped on far tier — bitmaps don't fake-blur, and they'd read as
    // a hard dot next to soft text.
    uint16_t blurCol = lerp565(0x2104, 0x4208, closeness * 4.0f);  // very dim
    drawText7seg(c, label.c_str(), tx,     ty,     textSize, blurCol);
    drawText7seg(c, label.c_str(), tx + 1, ty,     textSize, blurCol);
    drawText7seg(c, label.c_str(), tx,     ty + 1, textSize, blurCol);
  } else {
    drawText7seg(c, label.c_str(), tx, ty, textSize, textCol);

    // Icon to the right of the text. Size matches the text tier:
    //   selected (size 6, 48px tall) -> 48x48 icon
    //   near      (size 4, 32px tall) -> 32x32 icon
    // Recolored with the same textCol so it dims/brightens with the carousel.
    uint8_t iconSize = isSelected ? 48 : 32;
    uint8_t iw = 0, ih = 0;
    const unsigned char *bm = menuIconBitmap(labelIdx, iconSize, &iw, &ih);
    if (bm) {
      int16_t iconX = tx + (int16_t)w + 4;  // 4px gap after text
      int16_t iconY = ay - (int16_t)ih / 2; // vertically centered on arc point
      c->drawBitmap(iconX, iconY, bm, iw, ih, textCol);
    }
  }
}

void DisplayManager::drawMenu(uint8_t selectedIndex, int8_t scrollDir, float t) {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Half-circle arc: center on LEFT edge, vertically centered, 3px thick bright cyan
  const int16_t cx = 0;
  const int16_t cy = canvas->height() / 2;   // 120
  const int16_t r  = 115;
  const uint16_t arcColor = 0x07FF;
  canvas->drawCircle(cx, cy, r - 1, arcColor);
  canvas->drawCircle(cx, cy, r,     arcColor);
  canvas->drawCircle(cx, cy, r + 1, arcColor);

  const uint8_t count = MenuManager::menuItemCount();

  if (scrollDir == 0) {
    // Static: 3 items at -60, 0, +60 degrees
    float angles[3] = { -60.0f, 0.0f, 60.0f };
    uint8_t idx[3] = {
      (uint8_t)((selectedIndex + count - 1) % count),
      selectedIndex,
      (uint8_t)((selectedIndex + 1) % count)
    };
    for (int i = 0; i < 3; i++) {
      float close = (i == 1) ? 1.0f : 0.0f;
      drawMenuItem(canvas, cx, cy, r, angles[i], idx[i], close);
    }
  } else {
    // Animated: 4 items slide along the arc.
    // scrollDir=+1 (down): items move UP (angles decrease). The item that was
    //   BELOW (next) slides up to center, old selected slides up to top.
    //   New item enters from below. Like scrolling a list down.
    // scrollDir=-1 (up): items move DOWN (angles increase). The item that was
    //   ABOVE (prev) slides down to center, old selected slides down to bottom.
    //   New item enters from above. Like scrolling a list up.
    float shift = -scrollDir * 60.0f * t;

    uint8_t itemIdx[4];
    float baseAngles[4];

    if (scrollDir > 0) {
      // Scrolling down: items slide UP. New selected enters from BELOW.
      // [oldPrev, oldSel, newSel, newNext] at [-60, 0, +60, +120]
      itemIdx[0] = (selectedIndex + count - 2) % count;    // old prev (slides off top)
      itemIdx[1] = (selectedIndex + count - 1) % count;    // old selected (moves to top)
      itemIdx[2] = selectedIndex;                          // new selected (moves to center from below)
      itemIdx[3] = (selectedIndex + 1) % count;            // new next (enters from bottom)
      baseAngles[0] = -60; baseAngles[1] = 0; baseAngles[2] = 60; baseAngles[3] = 120;
    } else {
      // Scrolling up: items slide DOWN. New selected enters from ABOVE.
      // [newPrev, newSel, oldSel, oldNext] at [-120, -60, 0, +60]
      itemIdx[0] = (selectedIndex + count - 1) % count;    // new prev (enters from top)
      itemIdx[1] = selectedIndex;                          // new selected (moves to center from above)
      itemIdx[2] = (selectedIndex + 1) % count;            // old selected (moves to bottom)
      itemIdx[3] = (selectedIndex + 2) % count;            // old next (slides off bottom)
      baseAngles[0] = -120; baseAngles[1] = -60; baseAngles[2] = 0; baseAngles[3] = 60;
    }

    for (int i = 0; i < 4; i++) {
      float angle = baseAngles[i] + shift;
      // Skip items that have slid off the visible half-arc
      if (angle < -95.0f || angle > 95.0f) continue;
      // Closeness to center (angle 0): 1.0 at center, 0.0 at +/-60, negative beyond
      float closeness = 1.0f - fabs(angle) / 60.0f;
      drawMenuItem(canvas, cx, cy, r, angle, itemIdx[i], closeness);
    }
  }

  pushToDisplay();
}
