#include "DisplayManager.h"
#include "BatteryManager.h"
#include "RM67162Display.h"
#include "MenuManager.h"
#include "StopwatchManager.h"
#include "TimeManager.h"
#include "WeatherManager.h"
#include "config/config.h" // LATITUDE / LONGITUDE for Dusk2Dawn
#include "Dusk2Dawn.h"
#include "starfield_icons.h" // 7-seg digits, am/pm, wifi (from watchy-starfield)
#include "earth_landmask.h" // 1-bit equirectangular landmask (generated by icons/gen_earth_landmask.py)
#include "sevenseg_letters.h" // 7-seg letter bitmaps (generated by icons/gen_7seg_letters.py)
#include "battery_icons.h" // 1-bit battery state icons (generated from icons/battery/*.png)
#include "icons.h" // 1-bit PROGMEM menu icons (generated from icons/*.png)
#include "weather_icons.h" // 1-bit PROGMEM weather icons (generated from icons/weather/*.png)
#include "legend_icons.h" // 1-bit PROGMEM legend icons (generated from icons/*.png)
#include "face_icons.h" // 1-bit PROGMEM watch-face icons (thermometer/sunrise/sunset, 24x24)
#include "rm67162.h" // For lcd_PushColors
#include <math.h>
#include <WiFi.h>

static RM67162Display display;
GFXcanvas16 *DisplayManager::canvas = nullptr;

// ----- Starfield watch face helpers -----
// Adapted from watchy-starfield-main: 7-seg digit bitmaps, moon phase,
// sunrise/sunset, procedural starfield background. Layout is landscape
// (536x240) instead of the original 200x200 portrait e-paper.

// ponytail: 16-bit LCG for a deterministic starfield. Same seed → same stars
// every frame, so the background is stable across redraws. Ceiling: stars
// are fixed at boot; no drift/twinkle. Upgrade: animate with millis().
static uint32_t s_starSeed = 0x1234ABCD;
static inline uint32_t lcg16() {
  s_starSeed = s_starSeed * 1103515245u + 12345u;
  return (s_starSeed >> 16) & 0x7FFF;
}

// 7-seg big digit (33x53) lookup. fd_0..fd_9 from starfield_icons.h.
static const unsigned char *fdDigits[] = {
  fd_0, fd_1, fd_2, fd_3, fd_4, fd_5, fd_6, fd_7, fd_8, fd_9
};
// 7-seg small digit (16x25) lookup. dd_0..dd_9
static const unsigned char *ddDigits[] = {
  dd_0, dd_1, dd_2, dd_3, dd_4, dd_5, dd_6, dd_7, dd_8, dd_9
};
// 3x5 tiny digit lookup. num_0..num_9
static const unsigned char *numDigits[] = {
  num_0, num_1, num_2, num_3, num_4, num_5, num_6, num_7, num_8, num_9
};

// Draw a multi-digit 7-seg number at (x,y) using small 16x25 bitmaps.
static int drawSmallDigits(GFXcanvas16 *c, int value, int nDigits,
                           int16_t x, int16_t y, uint16_t color) {
  const int dw = 16, dh = 25, gap = 3;
  for (int i = nDigits - 1; i >= 0; i--) {
    int d = value % 10;
    value /= 10;
    int16_t dx = x + i * (dw + gap);
    c->drawBitmap(dx, y, ddDigits[d], dw, dh, color);
  }
  return nDigits * (dw + gap) - gap;
}

// Draw small L-shaped corner brackets around a bounding box.
// leg = length of each L arm in pixels.
static void drawCornerBrackets(GFXcanvas16 *c, int16_t x, int16_t y,
                               int16_t w, int16_t h, uint8_t leg,
                               uint16_t color) {
  if (w < 2 || h < 2) return;
  int16_t rx = x + w - 1, by = y + h - 1;
  // Top-left
  c->drawFastHLine(x, y, leg, color);
  c->drawFastVLine(x, y, leg, color);
  // Top-right
  c->drawFastHLine(rx - leg + 1, y, leg, color);
  c->drawFastVLine(rx, y, leg, color);
  // Bottom-left
  c->drawFastHLine(x, by, leg, color);
  c->drawFastVLine(x, by - leg + 1, leg, color);
  // Bottom-right
  c->drawFastHLine(rx - leg + 1, by, leg, color);
  c->drawFastVLine(rx, by - leg + 1, leg, color);
}

// Draw a 1-bit PROGMEM bitmap scaled by `sx`/`sy` (float for fine control).
// Used to make the 33x53 7-seg digits fill the top half of the screen, and
// to scale moon/icons by fractional amounts. fillRect per set pixel.
static void drawBitmapScaled(GFXcanvas16 *c, int16_t x, int16_t y,
                             const unsigned char *bm, int16_t w, int16_t h,
                             float sx, float sy, uint16_t color) {
  int16_t bytesPerRow = (w + 7) / 8;
  for (int16_t row = 0; row < h; row++) {
    for (int16_t col = 0; col < w; col++) {
      uint16_t byteIdx = row * bytesPerRow + col / 8;
      uint8_t bits = pgm_read_byte(&bm[byteIdx]);
      if (bits & (0x80 >> (col & 7))) {
        int16_t px = (int16_t)(col * sx);
        int16_t py = (int16_t)(row * sy);
        int16_t ex = (int16_t)((col + 1) * sx);
        int16_t ey = (int16_t)((row + 1) * sy);
        c->fillRect(x + px, y + py, ex - px, ey - py, color);
      }
    }
  }
}

// Draw n 33x53 7-seg digits scaled by `scale`, with `gap` px between digits.
static void drawBigDigitsScaled(GFXcanvas16 *c, int value, int nDigits,
                                int16_t x, int16_t y, int scale, int gap,
                                uint16_t color) {
  const int dw = 33, dh = 53;
  int step = dw * scale + gap;
  for (int i = nDigits - 1; i >= 0; i--) {
    int d = value % 10;
    value /= 10;
    drawBitmapScaled(c, x + i * step, y, fdDigits[d], dw, dh, scale, scale, color);
  }
}

// Draw a mixed alphanumeric 7-seg string using big 33x53 bitmaps, scaled.
// Handles digits 0-9, letters/punctuation from sevenseg_letters.h, ':'
// (two round dots via fillCircle for cleaner look), and ' ' (gap).
// Returns total width drawn. Unknown chars are skipped (zero width).
static int drawBigText7seg(GFXcanvas16 *c, const char *s,
                           int16_t x, int16_t y, int scale, int gap,
                           uint16_t color) {
  const int dw = 33, dh = 53;
  int step = dw * scale + gap;
  int16_t cx = x;
  for (const char *p = s; *p; p++) {
    char ch = *p;
    if (ch == ' ') { cx += step; continue; }
    if (ch == ':') {
      int16_t cy1 = y + dh * scale / 3;
      int16_t cy2 = y + dh * scale * 2 / 3;
      uint8_t r = scale >= 2 ? 2 * scale / 3 : 1;
      c->fillCircle(cx + dw * scale / 2, cy1, r, color);
      c->fillCircle(cx + dw * scale / 2, cy2, r, color);
      cx += step;
      continue;
    }
    const unsigned char *bm = nullptr;
    if (ch >= '0' && ch <= '9') bm = fdDigits[ch - '0'];
    else                        bm = fd_letterBitmap(ch);
    if (!bm) continue;
    drawBitmapScaled(c, cx, y, bm, dw, dh, scale, scale, color);
    cx += step;
  }
  return cx - x - gap;
}

// Draw a mixed alphanumeric 7-seg string using small 16x25 bitmaps.
// Returns total width drawn. Unknown chars are skipped.
static int drawSmallText7seg(GFXcanvas16 *c, const char *s,
                             int16_t x, int16_t y, int gap,
                             uint16_t color) {
  const int dw = 16, dh = 25;
  int step = dw + gap;
  int16_t cx = x;
  for (const char *p = s; *p; p++) {
    char ch = *p;
    if (ch == ' ') { cx += step; continue; }
    if (ch == ':') {
      c->fillCircle(cx + dw / 2, y + dh / 3, 2, color);
      c->fillCircle(cx + dw / 2, y + dh * 2 / 3, 2, color);
      cx += step;
      continue;
    }
    const unsigned char *bm = nullptr;
    if (ch >= '0' && ch <= '9') bm = ddDigits[ch - '0'];
    else                        bm = dd_letterBitmap(ch);
    if (!bm) continue;
    c->drawBitmap(cx, y, bm, dw, dh, color);
    cx += step;
  }
  return cx - x - gap;
}

// Draw small 16x25 7-seg text scaled by an integer factor (via drawBitmapScaled).
// For when you need the small font bigger but don't want the big 33x53 font.
static int drawSmallText7segScaled(GFXcanvas16 *c, const char *s,
                                   int16_t x, int16_t y, int scale, int gap,
                                   uint16_t color) {
  const int dw = 16, dh = 25;
  int step = dw * scale + gap;
  int16_t cx = x;
  for (const char *p = s; *p; p++) {
    char ch = *p;
    if (ch == ' ') { cx += step; continue; }
    if (ch == ':') {
      uint8_t r = scale >= 2 ? scale : 1;
      c->fillCircle(cx + dw * scale / 2, y + dh * scale / 3, r, color);
      c->fillCircle(cx + dw * scale / 2, y + dh * scale * 2 / 3, r, color);
      cx += step;
      continue;
    }
    const unsigned char *bm = nullptr;
    if (ch >= '0' && ch <= '9') bm = ddDigits[ch - '0'];
    else                        bm = dd_letterBitmap(ch);
    if (!bm) continue;
    drawBitmapScaled(c, cx, y, bm, dw, dh, scale, scale, color);
    cx += step;
  }
  return cx - x - gap;
}

// --- 7-seg text rendering (replaces former dot-matrix renderer) ---
// Maps a `size` param to the closest 7-seg font/scale. The 7-seg font has a
// different aspect ratio than the old dot-matrix font, so heights won't match
// exactly — layouts may need minor y adjustment.
//   size 1   → tiny  8x12  (gap 1)
//   size 2-3 → small 16x25 (gap 2-3)
//   size 4-5 → small 16x25 scaled 2x (gap 3)
//   size 6+  → big   33x53 (gap 4)
static void drawText7seg(GFXcanvas16 *c, const char *s, int16_t x, int16_t y,
                         uint8_t size, uint16_t color) {
  if (!c || !s || !*s) return;
  if (size <= 1) {
    // tiny 8x12 font
    const int dw = 8, dh = 12, gap = 1;
    int step = dw + gap;
    int16_t cx = x;
    for (const char *p = s; *p; p++) {
      char ch = *p;
      if (ch == ' ') { cx += step; continue; }
      if (ch == ':') {
        c->fillCircle(cx + dw / 2, y + dh / 3, 1, color);
        c->fillCircle(cx + dw / 2, y + dh * 2 / 3, 1, color);
        cx += step;
        continue;
      }
      const unsigned char *bm = td_letterBitmap(ch);
      if (!bm) continue;
      c->drawBitmap(cx, y, bm, dw, dh, color);
      cx += step;
    }
  } else if (size <= 3) {
    int gap = size <= 2 ? 2 : 3;
    drawSmallText7seg(c, s, x, y, gap, color);
  } else if (size <= 5) {
    drawSmallText7segScaled(c, s, x, y, 2, 3, color);
  } else {
    drawBigText7seg(c, s, x, y, 1, 4, color);
  }
}

static void text7segBounds(const char *s, uint8_t size, uint16_t *w, uint16_t *h) {
  if (!s) { if (w) *w = 0; if (h) *h = 0; return; }
  int n = (int)strlen(s);
  if (n == 0) { if (w) *w = 0; if (h) *h = 0; return; }
  int dw, dh, gap;
  if (size <= 1)        { dw =  8; dh = 12; gap = 1; }
  else if (size <= 3)   { dw = 16; dh = 25; gap = size <= 2 ? 2 : 3; }
  else if (size <= 5)   { dw = 32; dh = 50; gap = 3; }
  else                  { dw = 33; dh = 53; gap = 4; }
  if (w) *w = (uint16_t)(n * (dw + gap) - gap);
  if (h) *h = (uint16_t)dh;
}

// Draw an orthographic Earth globe centered on (cx,cy), radius R, geographically
// centered on (centerLat, centerLon) [radians]. Shades day/night terminator from
// sun declination `dec` [rad] and subsolar longitude `subLon` [rad]. The user's
// position is at the globe center (centered projection), drawn as a dot.
// ponytail: per-pixel inverse orthographic + zenith test on ~pi*R^2 pixels.
// At R=45 that's ~6360 px, each doing ~4 sin/cos + 1 atan2 + 1 asin in float.
// ESP32 handles it in a few ms per frame. Ceiling: animating every frame or
// enlarging R past ~120 would warrant a precomputed lat/lon LUT per radius.
// Twilight band: |cosZ| < TWILIGHT -> blend toward a dimmer shade for a soft
// terminator instead of a hard 1-px edge. Cheap 3-step, no per-channel lerp.
static void drawEarthGlobe(GFXcanvas16 *c, int16_t cx, int16_t cy, int16_t R,
                           double centerLat, double centerLon,
                           double dec, double subLon, uint16_t dotColor) {
  const double sinCL = sin(centerLat), cosCL = cos(centerLat);
  const double sinD  = sin(dec),       cosD  = cos(dec);
  // RGB565 palette — black & white like the old moon.
  //   Day:   sea = white, land = black
  //   Night: sea = dark gray, land = black   (hard terminator, no band)
  const uint16_t SEA_DAY   = 0xFFFF; // white
  const uint16_t SEA_NIGHT = 0x4208; // dark gray
  const uint16_t LAND_DAY  = 0x0000; // black
  const uint16_t LAND_NIGHT= 0x0000; // black
  const uint16_t RIM       = 0x8410; // dim gray outline
  // Whitish rim drawn around land masses on the night side only, so the
  // continents stay readable against the dark night ocean. Light gray
  // (~197,194,197) reads as "whitish" next to black land / dark-gray sea.
  const uint16_t NIGHT_LAND_RIM = 0xC618;

  int32_t R2 = (int32_t)R * R;
  // Per-pixel flags buffered during the fill so the night-side land outline
  // pass needs no second lat/lon derivation. bit0 = land, bit1 = night.
  // ponytail: static heap buffer resized when R changes; D*D bytes (8281 B at
  // R=45). Single-threaded display path, so static is safe. Ceiling: R>~140
  // would push the alloc past ~40 KB; fine on ESP32 PSRAM, revisit if needed.
  const int16_t D = 2 * R + 1;
  static uint8_t *flags = nullptr;
  static int16_t flagsDim = 0;
  if (flagsDim != D) { delete[] flags; flags = new uint8_t[D * D]; flagsDim = D; }
  memset(flags, 0, D * D); // 0 = sea+day -> safely skipped by the outline pass

  for (int16_t dy = -R; dy <= R; dy++) {
    int16_t py = cy + dy;
    if (py < 0 || py >= c->height()) continue;
    int16_t xspan = (int16_t)sqrtf((float)(R2 - (int32_t)dy * dy));
    for (int16_t dx = -xspan; dx <= xspan; dx++) {
      int16_t px = cx + dx;
      if (px < 0 || px >= c->width()) continue;
      double lat, lon;
      float rho = sqrtf((float)(dx * dx + dy * dy));
      if (rho < 0.5f) {
        lat = centerLat; lon = centerLon;
      } else {
        // screen y is down; geographic lat is up -> use -dy for north.
        double c_ang = asin((double)rho / R);
        double sc = sin(c_ang), cc = cos(c_ang);
        double ux =  dx / rho, uy = -dy / rho; // unit screen vector (east, north)
        lat = asin(cc * sinCL + uy * sc * cosCL);
        lon = centerLon + atan2(ux * sc, cc * cosCL - uy * sc * sinCL);
      }
      bool land = earthIsLand(lat * 180.0 / M_PI, lon * 180.0 / M_PI);
      double cosZ = sin(lat) * sinD + cos(lat) * cosD * cos(lon - subLon);
      bool night = (cosZ <= 0.0);
      uint16_t col = night ? (land ? LAND_NIGHT : SEA_NIGHT)
                           : (land ? LAND_DAY : SEA_DAY);
      c->drawPixel(px, py, col);
      flags[(dy + R) * D + (dx + R)] = (land ? 1 : 0) | (night ? 2 : 0);
    }
  }

  // Night-side land outline: draw NIGHT_LAND_RIM on shadowed land pixels that
  // border sea (4-neighbour). Out-of-disc neighbours are treated as non-sea so
  // the globe rim itself isn't mistaken for a coastline. O(D^2), ~8k px at
  // R=45, negligible vs the trig-heavy fill pass.
  auto neighbourIsSea = [&](int16_t nx, int16_t ny) -> bool {
    if ((int32_t)nx * nx + (int32_t)ny * ny > R2) return false;
    return !(flags[(ny + R) * D + (nx + R)] & 1);
  };
  for (int16_t dy = -R; dy <= R; dy++) {
    int16_t xspan = (int16_t)sqrtf((float)(R2 - (int32_t)dy * dy));
    for (int16_t dx = -xspan; dx <= xspan; dx++) {
      uint8_t f = flags[(dy + R) * D + (dx + R)];
      if (!(f & 2) || !(f & 1)) continue; // night + land only
      if (neighbourIsSea(dx - 1, dy) || neighbourIsSea(dx + 1, dy) ||
          neighbourIsSea(dx, dy - 1) || neighbourIsSea(dx, dy + 1))
        c->drawPixel(cx + dx, cy + dy, NIGHT_LAND_RIM);
    }
  }

  c->drawCircle(cx, cy, R, RIM);
  // User position is the projection center -> dot at disc center.
  c->fillCircle(cx, cy, 2, dotColor);
}

void DisplayManager::initDisplay() {
  display.begin();
  display.setRotation(1);     // Landscape
  display.fillScreen(0x0000); // Clear initial screen

  // Allocate framebuffer in PSRAM if possible, otherwise heap
  // 536 * 240 * 2 = 257,280 bytes
  canvas = new GFXcanvas16(display.width(), display.height());
  if (canvas) {
    Serial.println("Canvas allocated successfully");
  } else {
    Serial.println("Canvas allocation FAILED!");
  }
}

void DisplayManager::pushToDisplay() {
  if (canvas) {
    lcd_PushColors(0, 0, canvas->width(), canvas->height(),
                   canvas->getBuffer());
  }
}

// ISO 8601 week number from a filled struct tm.
// ponytail: Thursday-of-week method — the ISO week belongs to the year of its
// Thursday, so we compute the Thursday's day-of-year and divide by 7. Edge cases
// (Thursday in prev/next year) resolve to that year's last/first week. The
// prev-year fallback computes Jan 1 weekday to distinguish 52 vs 53.
static int isoWeek(const struct tm &t) {
  int isoWday = (t.tm_wday == 0) ? 7 : t.tm_wday; // Mon=1..Sun=7
  int doy = t.tm_yday + 1;                        // 1-based day of year
  int thuDoy = doy + (4 - isoWday);               // Thursday of this ISO week
  int y = t.tm_year + 1900;
  auto leap = [](int yr) { return (yr%4==0 && yr%100!=0) || (yr%400==0); };
  int yearLen = 365 + (leap(y) ? 1 : 0);
  if (thuDoy < 1) {
    int py = y - 1;
    int jan1Wday = ((isoWday - (doy - 1) - 1) % 7 + 7) % 7 + 1;
    int prevLen = 365 + (leap(py) ? 1 : 0);
    int prevJan1Wday = ((jan1Wday - (prevLen % 7) - 1) % 7 + 7) % 7 + 1;
    bool has53 = (prevJan1Wday == 4) || (leap(py) && prevJan1Wday == 3);
    return has53 ? 53 : 52;
  }
  if (thuDoy > yearLen) return 1;
  return (thuDoy - 1) / 7 + 1;
}

void DisplayManager::drawWatchFace(const String &timeStr) {
  if (!canvas)
    return;

  // ----- Starfield watch face (adapted from watchy-starfield-main) -----
  // Layout (536x240 landscape):
  //   Left two-thirds (0-360), split horizontally:
  //     Top half  (0-120):   Big 7-seg clock, scaled to fill
  //     Bottom half (120-240): Date (DOW + W## on left, DD.MM / YYYY on right)
  //   Right third (360-536): Earth globe (day/night + position dot), wifi, temp
//   Day progress bar: under the clock (24h, dotted sleeping edges + now marker)
  //   Battery icon (32x32): top-right corner, left of the globe

  canvas->fillScreen(0x0000); // black background

  // Fetch local time once for all date/Earth/sun calculations below.
  struct tm timeinfo;
  bool haveTime = getLocalTime(&timeinfo, 10);

  // --- Parse time string "HH:MM:SS" ---
  int hh = timeStr.substring(0, 2).toInt();
  int mm = timeStr.substring(3, 5).toInt();

  // --- Top section: big scaled 7-seg clock ---
  // Digit native 33x53. Scale 2 → 66x106. Top section ~120px tall, fits.
  // Width = 4 digits + 3 inter-digit gaps + colon. drawBigDigitsScaled uses
  // step = dw*scale + gap, so a pair spans step + dw = 144, not 2*dw = 132.
  // ponytail: clockW must match the actual rightmost pixel of MM's last digit,
  // not a naive 4*dw + colon + 2*gap — that undercounts by one inter-digit gap
  // and the corner brackets end up overlapping the time.
  const uint16_t TIME_COLOR = 0xFFFF; // white
  const int SCALE = 2;
  const int DW = 33 * SCALE;  // 66
  const int DH = 53 * SCALE;  // 106
  const int DGAP = 12;
  const int COLON_W = 16;
  int clockW = 4 * DW + 3 * DGAP + COLON_W;  // 316
  const int16_t leftSpan = 360;
  int16_t timeX = (leftSpan - clockW) / 2;     // centered in left 2/3
  int16_t timeY = (120 - DH) / 2;             // centered in top half
  if (timeY < 2) timeY = 2;

  // HH
  drawBigDigitsScaled(canvas, hh, 2, timeX, timeY, SCALE, DGAP, TIME_COLOR);
  // Colon (two dots) between HH and MM
  int16_t colonX = timeX + 2 * DW + DGAP + COLON_W / 2;
  int16_t colonY = timeY + DH / 2;
  canvas->fillCircle(colonX, colonY - 10, 4, TIME_COLOR);
  canvas->fillCircle(colonX, colonY + 10, 4, TIME_COLOR);
  // MM
  drawBigDigitsScaled(canvas, mm, 2, timeX + 2 * DW + DGAP + COLON_W + DGAP,
                      timeY, SCALE, DGAP, TIME_COLOR);

  // --- Bottom section: date ---
  // Layout: [DOW]  [DD.MM]   (DOW on left, date on right, two rows)
  //                [YYYY]
  // DOW sized to match the date block height (~54px → dot size 7 = 56px).
  // Group pushed to the lower-left corner of the screen.
  const uint16_t DATE_COLOR = 0xBDF7; // light blue-white
  const uint16_t LABEL_COLOR = 0x7BEF; // gray

  String dateStr = TimeManager::getCurrentDate(); // "Mon 25/12"

  // Parse day and month from "Mon 25/12"
  int dayNum = 0, monthNum = 0;
  int slashIdx = dateStr.indexOf('/');
  if (slashIdx > 0) {
    int spaceIdx = dateStr.indexOf(' ');
    if (spaceIdx >= 0) {
      dayNum = dateStr.substring(spaceIdx + 1, slashIdx).toInt();
      monthNum = dateStr.substring(slashIdx + 1).toInt();
    }
  }
  int year = haveTime ? timeinfo.tm_year + 1900 : 2025;

  // Measure both blocks.
  const int SDW = 16, SDH = 25, SGAP = 3, DOTW = 6, DDOT_GAP = 4;
  int dateRowW = 2 * (SDW + 3) + DOTW + 2 * (SDW + 3); // DD . MM
  int yearW = 4 * SDW + 3 * SGAP;
  int dateBlockW = (dateRowW > yearW) ? dateRowW : yearW;
  int dateBlockH = SDH + 4 + SDH; // two rows of 25px + 4px gap = 54

  // DOW dot text at size 3 → 8*3 = 24px tall, matches the top row (25px).
  // Bottom row of the DOW column shows "W" + ISO week number.
  const uint8_t DOW_SIZE = 3;
  uint16_t dowW = 0, dowH = 0;
  String dow;
  if (dateStr.length() >= 3) {
    dow = dateStr.substring(0, 3); // "Mon"
    text7segBounds(dow.c_str(), DOW_SIZE, &dowW, &dowH);
  }

  const int COL_GAP = 16;
  int groupW = dowW + COL_GAP + dateBlockW;
  // Push to lower-left: left edge aligned with the progress bar (= timeX).
  int16_t groupX = timeX;
  int16_t groupY = canvas->height() - dateBlockH - 8;
  if (groupY < 122) groupY = 122; // don't cross into top section

  // DOW in the top row (aligned with DD.MM), W## in the bottom row (aligned with YYYY)
  // ponytail: DOW, "W", and week number in gray (LABEL_COLOR) to de-emphasize vs date.
  int16_t dowY = groupY + (SDH - dowH) / 2; // vertically centered in top row
  if (dow.length()) {
    drawText7seg(canvas, dow.c_str(), groupX, dowY, DOW_SIZE, LABEL_COLOR);
  }

  // Week number in the bottom row of the DOW column
  int16_t weekY = groupY + SDH + 4; // same baseline as YYYY row
  drawText7seg(canvas, "W", groupX, weekY + (SDH - 24) / 2, DOW_SIZE, LABEL_COLOR);
  if (haveTime) {
    int wk = isoWeek(timeinfo);
    drawSmallDigits(canvas, wk, 2, groupX + 6 * DOW_SIZE + 2, weekY, DATE_COLOR);
  } else {
    drawSmallDigits(canvas, 0, 2, groupX + 6 * DOW_SIZE + 2, weekY, DATE_COLOR);
  }

  // Date block on the right of DOW
  int16_t dbX = groupX + dowW + COL_GAP;
  int16_t dbY = groupY;

  // Row 1: DD . MM
  if (dayNum > 0) {
    int16_t dx = dbX + (dateBlockW - dateRowW) / 2;
    drawSmallDigits(canvas, dayNum, 2, dx, dbY, DATE_COLOR);
    int16_t dotX = dx + 2 * (SDW + 3) + DDOT_GAP / 2;
    canvas->fillCircle(dotX, dbY + SDH / 2 - 3, 2, DATE_COLOR);
    canvas->fillCircle(dotX, dbY + SDH / 2 + 3, 2, DATE_COLOR);
    drawSmallDigits(canvas, monthNum, 2,
                    dx + 2 * (SDW + 3) + DOTW + DDOT_GAP, dbY, DATE_COLOR);
  }

  // Row 2: YYYY
  int16_t yx = dbX + (dateBlockW - yearW) / 2;
  drawSmallDigits(canvas, year, 4, yx, dbY + SDH + 4, DATE_COLOR);

  // --- Top-right corner: wifi icon + battery icon ---
  // Wifi (25x18 → 31x23) and battery (32x32 → 40x40), both in white.
  bool wifiOn = (WiFi.status() == WL_CONNECTED);
  int batPct = BatteryManager::getPercentage();
  uint8_t batIw = 0, batIh = 0;
  // ponytail: charging == USB cable plugged (VBUS present). Two signals:
  // 1. HWCDCSerial.isPlugged() — SOF packets from a USB host (PC/data cable).
  // 2. BatteryManager::isUsbPowerConnected() — ADC voltage >4.4V on GPIO4,
  //    which detects dumb chargers that don't send SOF. The T-Display-S3
  //    AMOLED has no VBUS GPIO, so the ADC threshold is the only software
  //    option for charger detection. Upgrade: wire a GPIO to VBUS.
  bool charging = HWCDCSerial.isPlugged() || BatteryManager::isUsbPowerConnected();
  const unsigned char *batIcon = charging
      ? (batIw = 32, batIh = 32, BATICON_BATTERY_CHARGING)
      : batteryIconBitmap(batPct, &batIw, &batIh);
  const uint16_t ICON_COLOR = 0xFFFF; // white
  const int16_t topRightMargin = 4;
  // Battery: native 32x32 → target 40x40
  const int16_t BAT_TW = 40, BAT_TH = 40;
  float batSx = (float)BAT_TW / batIw;
  float batSy = (float)BAT_TH / batIh;
  int16_t batX = canvas->width() - BAT_TW - topRightMargin;
  int16_t topIconY = topRightMargin;
  if (batIcon) {
    drawBitmapScaled(canvas, batX, topIconY, batIcon, batIw, batIh,
                     batSx, batSy, ICON_COLOR);
  }
  // Wifi icon to the left of the battery, vertically centered with it.
  // Native 25x18 → target 31x23
  const int WIFI_W = 25, WIFI_H = 18;
  const int16_t WIFI_TW = 31, WIFI_TH = 23;
  float wifiSx = (float)WIFI_TW / WIFI_W;
  float wifiSy = (float)WIFI_TH / WIFI_H;
  int16_t wifiX = batX - WIFI_TW - 6;
  int16_t wifiY = topIconY + (BAT_TH - WIFI_TH) / 2;
  drawBitmapScaled(canvas, wifiX, wifiY, wifiOn ? wifi : wifioff,
                   WIFI_W, WIFI_H, wifiSx, wifiSy, ICON_COLOR);

  // --- Right column: Earth globe + sunrise/sunset + temp ---
  // Orthographic globe 120x120 (R=60), centered geographically on the user's
  // location so the user's face of Earth (Europe, for Copenhagen) is shown
  // and the position dot sits at the disc center. x=414, ends at 534.
  // SR/SS times are stacked vertically in the dead space between clock
  // (ends ~332) and globe (starts 414), below the globe's vertical extent.
  // ponytail: globe sized to fill the column width (122px) and shifted down
  // to close the dead space between the globe and the temperature readout.
  const int16_t rightX = 408;
  const int GLOBE_SIZE = 120;
  const int GLOBE_R = GLOBE_SIZE / 2;          // 60
  const int16_t globeY = 66;
  const int16_t globeX = rightX;
  const int16_t globeCx = globeX + GLOBE_R;
  const int16_t globeCy = globeY + GLOBE_R;

  // User location + UTC offset (shared by the globe terminator and Dusk2Dawn).
  float lat = String(LATITUDE).toFloat();
  float lon = String(LONGITUDE).toFloat();
  float tzOffset = 0;
  if (haveTime) {
    time_t now = mktime(&timeinfo);
    struct tm utc;
    gmtime_r(&now, &utc);
    tzOffset = (float)(timeinfo.tm_hour - utc.tm_hour) +
               (float)(timeinfo.tm_min - utc.tm_min) / 60.0f;
    if (tzOffset > 12)  tzOffset -= 24;
    if (tzOffset < -12) tzOffset += 24;
  }

  // Sun geometry for the day/night terminator.
  // ponytail: declination from the standard day-of-year approximation
  // (good to ~0.5 deg); subsolar longitude from UTC hours ignoring the
  // equation of time (good to ~0.5 deg). Both well within a 120px globe.
  //   dec       = -23.44 deg * cos(2pi/365 * (N+10))   N = day of year
  //   subLon    = (12 - utcHours) * 15 deg             utcHours = local - tz
  {
    int doy = haveTime ? timeinfo.tm_yday + 1 : 1;        // 1..365
    double decDeg = -23.44 * cos(2.0 * M_PI / 365.0 * (doy + 10));
    double utcHours = haveTime
      ? (timeinfo.tm_hour + timeinfo.tm_min / 60.0 - tzOffset)
      : 12.0;
    double subLonDeg = (12.0 - utcHours) * 15.0;
    while (subLonDeg >  180.0) subLonDeg -= 360.0;
    while (subLonDeg < -180.0) subLonDeg += 360.0;
    drawEarthGlobe(canvas, globeCx, globeCy, GLOBE_R,
                   lat * M_PI / 180.0, lon * M_PI / 180.0,
                   decDeg * M_PI / 180.0, subLonDeg * M_PI / 180.0,
                   0xF800); // red position dot
  }

  // Sunrise/sunset via Dusk2Dawn
  Dusk2Dawn d2d(lat, lon, tzOffset);
  int sr = -1, ss = -1;
  if (haveTime) {
    sr = d2d.sunrise(timeinfo.tm_year + 1900, timeinfo.tm_mon + 1,
                     timeinfo.tm_mday, false);
    ss = d2d.sunset(timeinfo.tm_year + 1900, timeinfo.tm_mon + 1,
                    timeinfo.tm_mday, false);
  }

  const uint16_t SUN_COLOR = 0xFD20; // orange
  const uint16_t SUN_LABEL_COLOR = 0xBDF7; // light blue-white

  // SR/SS times: inline (label next to time), stacked vertically at the
  // left, aligned with the date group rows. Frees vertical space under the
  // clock for the day bar to sit lower.
  if (sr >= 0 && ss >= 0) {
    int srH = sr / 60, srM = sr % 60;
    int ssH = ss / 60, ssM = ss % 60;

    // Right-aligned to the progress bar's right edge (timeX + clockW).
    // ponytail: 24x24 sunrise/sunset icons replace the old "SR"/"SS" text labels.
    const int16_t iconW = 24, iconH = 24;
    const int16_t labelGap = 4;
    // Block width: icon + gap + HH digits + colon gap + MM digits
    const int16_t ssW = iconW + labelGap + 2*(16+3) + 4 + (2*(16+3) - 3); // 105
    const int16_t ssX = timeX + clockW - ssW; // right-aligned to bar
    const int16_t digitX = ssX + iconW + labelGap;
    const int16_t srY = 178;      // aligned with date group top row
    const int16_t ssY = 178 + 25 + 4; // aligned with date group bottom row
    const int16_t iconYOff = 0;  // 24px icon in 25px row, ~centered

    // SR (sunrise icon)
    canvas->drawBitmap(ssX, srY + iconYOff, FICON_SUNRISE, iconW, iconH, SUN_COLOR);
    drawSmallDigits(canvas, srH, 2, digitX, srY, SUN_LABEL_COLOR);
    int16_t srColonX = digitX + 2 * (16 + 3);
    canvas->fillCircle(srColonX, srY + 8, 2, SUN_LABEL_COLOR);
    canvas->fillCircle(srColonX, srY + 16, 2, SUN_LABEL_COLOR);
    drawSmallDigits(canvas, srM, 2, srColonX + 4, srY, SUN_LABEL_COLOR);

    // SS (sunset icon)
    canvas->drawBitmap(ssX, ssY + iconYOff, FICON_SUNSET, iconW, iconH, SUN_COLOR);
    drawSmallDigits(canvas, ssH, 2, digitX, ssY, SUN_LABEL_COLOR);
    int16_t ssColonX = digitX + 2 * (16 + 3);
    canvas->fillCircle(ssColonX, ssY + 8, 2, SUN_LABEL_COLOR);
    canvas->fillCircle(ssColonX, ssY + 16, 2, SUN_LABEL_COLOR);
    drawSmallDigits(canvas, ssM, 2, ssColonX + 4, ssY, SUN_LABEL_COLOR);
  } else {
    drawText7seg(canvas, "Sun: N/A", timeX + clockW - 80, 190, 1, LABEL_COLOR);
  }

  // --- Day progress bar under the clock ---
  // Full 24h (midnight→midnight). Dotted edges = sleeping (night: 0→sunrise,
  // sunset→1440). Clear middle = awake (sunrise→sunset). Triangle = now.
  // ponytail: hatch is a fixed 3px-pitch diagonal scan; at barH=20 the
  // diagonals still cover without gaps. Enlarge past ~24 and upgrade to a
  // tiled PROGMEM pattern.
  if (sr >= 0 && ss >= 0) {
    const int16_t barX = timeX;
    const int16_t barY = 140;
    const int16_t barW = clockW;
    const int16_t barH = 20;
    const uint16_t DOT_COLOR = 0x6B4E; // lighter blue-gray, sleepy

    // Dotted sleeping edges first, then border on top.
    // ponytail: uniform 3px-pitch dot grid. At barH=20 this yields 6 rows,
    // enough to read as a fill. Enlarge past ~30 tall and bump to r=1 dots.
    int16_t srX = barX + (int32_t)sr * barW / 1440;
    int16_t ssX = barX + (int32_t)ss * barW / 1440;
    for (int16_t dy = 2; dy < barH - 1; dy += 3) {
      for (int16_t dx = 2; dx < barW - 1; dx += 3) {
        int16_t px = barX + dx;
        if (px >= srX && px < ssX) continue; // skip awake middle
        canvas->drawPixel(px, barY + dy, DOT_COLOR);
      }
    }
    canvas->drawRect(barX, barY, barW, barH, LABEL_COLOR);

    // Triangle marker (current time) above the bar, pointing down.
    int nowMin = timeinfo.tm_hour * 60 + timeinfo.tm_min;
    int16_t mx = barX + (int32_t)nowMin * barW / 1440;
    if (mx < barX + 4) mx = barX + 4;
    if (mx > barX + barW - 4) mx = barX + barW - 4;
    canvas->fillTriangle(mx, barY, mx - 4, barY - 6, mx + 4, barY - 6, SUN_COLOR);
  }

  // Temperature (white, right column, aligned vertically with SS time)
  // ponytail: 24x24 thermometer icon replaces the old "T:" text label.
  const uint16_t TEMP_COLOR = 0xFFFF; // white
  const int16_t TICON_W = 24, TICON_H = 24;
  String tempStr = WeatherManager::getTemperature();
  bool tempValid = tempStr.length() > 0 &&
                   (isDigit(tempStr.charAt(0)) || tempStr.charAt(0) == '-');
  if (tempValid) {
    canvas->drawBitmap(rightX, 207, FICON_THERMOMETER, TICON_W, TICON_H, TEMP_COLOR);
    int dotPos = tempStr.indexOf('.');
    int tempInt = (dotPos > 0) ? tempStr.substring(0, dotPos).toInt()
                                : tempStr.toInt();
    if (tempInt < 0) {
      drawText7seg(canvas, "-", rightX + 24, 207, 2, TEMP_COLOR);
      drawSmallDigits(canvas, -tempInt, 2, rightX + 44, 207, TEMP_COLOR);
    } else {
      drawSmallDigits(canvas, tempInt, 2, rightX + 24, 207, TEMP_COLOR);
    }
    drawText7seg(canvas, "C", rightX + 2 * (16 + 3) + 44, 207, 2, TEMP_COLOR);
  } else {
    canvas->drawBitmap(rightX, 207, FICON_THERMOMETER, TICON_W, TICON_H, LABEL_COLOR);
    drawText7seg(canvas, "--", rightX + 24, 207, 2, LABEL_COLOR);
  }

  // --- Corner brackets around each section ---
  const uint16_t BRACKET_COLOR = LABEL_COLOR; // gray
  const uint8_t BRACKET_LEG = 8;
  // Time (top-left, scaled clock)
  drawCornerBrackets(canvas, timeX - 4, timeY - 4,
                     clockW + 8, DH + 8, BRACKET_LEG, BRACKET_COLOR);
  // Calendar (lower-left, DOW + date block)
  drawCornerBrackets(canvas, groupX - 4, groupY - 4,
                     groupW + 8, dateBlockH + 8, BRACKET_LEG, BRACKET_COLOR);
  // Earth globe (right, 120x120)
  drawCornerBrackets(canvas, globeX - 4, globeY - 4,
                     GLOBE_SIZE + 8, GLOBE_SIZE + 8, BRACKET_LEG, BRACKET_COLOR);
  // SR/SS inline times (right-aligned to progress bar)
  {
    const int16_t ssW = 24 + 4 + 2*(16+3) + 4 + (2*(16+3) - 3); // 105
    drawCornerBrackets(canvas, timeX + clockW - ssW - 4, 174, ssW + 8, 62,
                       BRACKET_LEG, BRACKET_COLOR);
  }
  // Temperature (right column, aligned with SS time)
  // ponytail: width matches the globe bracket above so the stacked brackets
  // share the same right edge, and it encompasses the trailing "C" unit.
  drawCornerBrackets(canvas, rightX - 4, 203, GLOBE_SIZE + 8, 33, BRACKET_LEG,
                     BRACKET_COLOR);

  // Push buffer to display
  pushToDisplay();
}

void DisplayManager::drawWeatherScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Display is 536 wide x 240 tall (landscape).
  // Layout:
  //   0-30:    Title + current temp + weather icon
  //  35-165:   Graph area (temperature line + precipitation fill)
  // 170-178:   Hour labels under graph
  // 185-235:   Legend + min/max + location (single row, 536px wide)

  // --- Title ---
  drawText7seg(canvas, "WEATHER", 10, 5, 3, 0xFFE0); // yellow, size 3

  if (!WeatherManager::hasHourlyData()) {
    drawText7seg(canvas, "Fetching forecast...", 10, 40, 2, 0x7BEF);
    drawText7seg(canvas, "Updates every 10 min", 10, 65, 1, 0x7BEF);
    pushToDisplay();
    return;
  }

  const HourlyForecast &fc = WeatherManager::getHourlyForecast();
  uint8_t n = fc.count;
  if (n == 0) {
    drawText7seg(canvas, "No data", 10, 40, 2, 0xF800);
    pushToDisplay();
    return;
  }

  // --- Current weather icon (top-right) ---
  uint8_t iw = 0, ih = 0;
  const unsigned char *icon = weatherIconBitmap(fc.weatherCode[0], &iw, &ih);
  if (icon) {
    canvas->drawBitmap(canvas->width() - iw - 10, 5, icon, iw, ih, 0xFFFF);
  }

  // --- Current temperature text (below title) ---
  String currTemp = String((int)round(fc.temperature[0]));
  drawText7seg(canvas, (currTemp + "C").c_str(), 140, 12, 2, 0xFFFF); // white, size 2

  // --- Graph area ---
  // ponytail: graph leaves 34px on the left for the temperature ruler labels.
  // Temperature is a red line, precipitation is a light-blue filled area.
  // Both share the same x-axis (hours). Y-axes are independent.
  const int16_t rulerW = 24;
  const int16_t graphX = 10 + rulerW;           // 34
  const int16_t graphW = canvas->width() - 20 - rulerW;  // 492px
  const int16_t graphY = 35;
  const int16_t graphH = 160;
  const int16_t graphBottom = graphY + graphH;  // 195

  // Guard against single data point (division by zero in x mapping)
  if (n < 2) {
    int16_t x = graphX + graphW / 2;
    int16_t y = graphY + graphH / 2;
    canvas->fillCircle(x, y, 3, 0xF800);
    pushToDisplay();
    return;
  }

  // Find min/max for temperature scaling
  float tempMin = fc.temperature[0], tempMax = fc.temperature[0];
  float precipMax = 0.0f;
  for (uint8_t i = 0; i < n; i++) {
    if (fc.temperature[i] < tempMin) tempMin = fc.temperature[i];
    if (fc.temperature[i] > tempMax) tempMax = fc.temperature[i];
    if (fc.precipitation[i] > precipMax) precipMax = fc.precipitation[i];
  }
  // Snap to integer bounds so ruler ticks align exactly with the temperature
  // line. Floor the min, ceil the max, then pad by 1 degree so the line
  // doesn't touch the graph edges.
  tempMin = floorf(tempMin);
  tempMax = ceilf(tempMax);
  if (tempMax - tempMin < 2.0f) { tempMin -= 1.0f; tempMax += 1.0f; }
  tempMin -= 1.0f;
  tempMax += 1.0f;
  if (precipMax < 0.1f) precipMax = 1.0f; // avoid div-by-zero, show flat baseline

  // --- Precipitation area (light blue fill) ---
  // ponytail: filled area chart using vertical strips per data point.
  // RGB565 light blue: 0x4B5F (approx #29B5FE)
  const uint16_t PRECIP_COLOR = 0x4B5F;

  for (uint8_t i = 0; i < n; i++) {
    int16_t x = graphX + (int16_t)(graphW * i) / (n - 1);
    int16_t xNext = (i + 1 < n) ? graphX + (int16_t)(graphW * (i + 1)) / (n - 1) : x + 1;

    float precipH = (fc.precipitation[i] / precipMax) * (graphH * 0.5f);
    int16_t barH = (int16_t)precipH;

    // Draw filled bar from bottom up
    if (barH > 0) {
      canvas->fillRect(x, graphBottom - barH, xNext - x, barH, PRECIP_COLOR);
    }
  }

  // --- Temperature line (red) ---
  // ponytail: connected line graph. RGB565 red: 0xF800
  const uint16_t TEMP_COLOR = 0xF800;

  auto tempY = [&](float t) -> int16_t {
    float frac = (t - tempMin) / (tempMax - tempMin);
    return graphBottom - (int16_t)(frac * graphH);
  };

  for (uint8_t i = 1; i < n; i++) {
    int16_t x0 = graphX + (int16_t)(graphW * (i - 1)) / (n - 1);
    int16_t y0 = tempY(fc.temperature[i - 1]);
    int16_t x1 = graphX + (int16_t)(graphW * i) / (n - 1);
    int16_t y1 = tempY(fc.temperature[i]);
    canvas->drawLine(x0, y0, x1, y1, TEMP_COLOR);
  }

  // Draw data points as small circles
  for (uint8_t i = 0; i < n; i++) {
    int16_t x = graphX + (int16_t)(graphW * i) / (n - 1);
    int16_t y = tempY(fc.temperature[i]);
    canvas->fillCircle(x, y, 2, TEMP_COLOR);
  }

  // --- Peak / Low / Average temperature annotations ---
  // ponytail: peak label sits below the point, low label above, average at the
  // hour whose temp is closest to the mean. Size-1 text (8x12) keeps it compact.
  // Ceiling: labels can collide on tight clusters or at graph edges; no overlap
  // avoidance. Upgrade: shift label x by text width when near right edge.
  uint8_t peakIdx = 0, lowIdx = 0;
  float sum = 0.0f;
  for (uint8_t i = 0; i < n; i++) {
    if (fc.temperature[i] > fc.temperature[peakIdx]) peakIdx = i;
    if (fc.temperature[i] < fc.temperature[lowIdx])  lowIdx  = i;
    sum += fc.temperature[i];
  }
  float avg = sum / n;
  uint8_t avgIdx = 0;
  float bestDiff = fabsf(fc.temperature[0] - avg);
  for (uint8_t i = 1; i < n; i++) {
    float d = fabsf(fc.temperature[i] - avg);
    if (d < bestDiff) { bestDiff = d; avgIdx = i; }
  }

  const uint16_t PEAK_COLOR = 0xFFE0; // yellow
  const uint16_t LOW_COLOR  = 0x07FF; // cyan
  const uint16_t AVG_COLOR  = 0x07E0; // green
  const int16_t lblH = 12;            // size-1 text height
  const int16_t lblW = 8;             // size-1 char width (approx, per digit)

  auto drawTempLabel = [&](uint8_t idx, int16_t yOff, uint16_t color) {
    int16_t x = graphX + (int16_t)(graphW * idx) / (n - 1);
    int16_t y = tempY(fc.temperature[idx]) + yOff;
    char buf[8];
    snprintf(buf, sizeof(buf), "%d", (int)round(fc.temperature[idx]));
    // Center the label horizontally on the point
    int16_t textW = (int16_t)(strlen(buf) * (lblW + 1));
    int16_t lx = x - textW / 2;
    // Clamp inside graph area
    if (lx < graphX) lx = graphX;
    if (lx + textW > graphX + graphW) lx = graphX + graphW - textW;
    drawText7seg(canvas, buf, lx, y, 1, color);
  };

  drawTempLabel(peakIdx,  4,           PEAK_COLOR); // below peak
  drawTempLabel(lowIdx,  -(lblH + 2),  LOW_COLOR);  // above low
  // Average: label sits at the avg temp's y (middle of the temp band) at the
  // hour where the curve is closest to the average.
  {
    int16_t ax = graphX + (int16_t)(graphW * avgIdx) / (n - 1);
    int16_t ay = tempY(avg) - lblH / 2;
    char buf[8];
    snprintf(buf, sizeof(buf), "%d", (int)round(avg));
    int16_t textW = (int16_t)(strlen(buf) * (lblW + 1));
    int16_t lx = ax - textW / 2;
    if (lx < graphX) lx = graphX;
    if (lx + textW > graphX + graphW) lx = graphX + graphW - textW;
    drawText7seg(canvas, buf, lx, ay, 1, AVG_COLOR);
  }

  // --- Graph border ---
  canvas->drawRect(graphX, graphY, graphW, graphH, 0x4208); // dark gray border

  // --- Temperature ruler (left side) ---
  // ponytail: 3 tick marks + labels (max, mid, min) aligned to the graph's y-scale.
  // Shows the actual temp range so you can read values off the red line.
  const uint16_t RULER_COLOR = 0x8410; // dark gray
  int tempHi = (int)tempMax; // already integer-bounded + padded
  int tempLo = (int)tempMin;
  int tempMid = (tempHi + tempLo) / 2;

  struct { int16_t y; int val; } ticks[] = {
    { graphY,              tempHi },
    { graphY + graphH / 2, tempMid },
    { graphBottom,        tempLo },
  };
  for (auto &t : ticks) {
    // tick mark on the left edge of the graph
    canvas->drawLine(graphX - 4, t.y, graphX, t.y, RULER_COLOR);
    // label just left of the tick
    char buf[8];
    snprintf(buf, sizeof(buf), "%d", t.val);
    drawText7seg(canvas, buf, graphX - 22, t.y - 4, 1, 0x7BEF);
  }

  // --- Hour labels under graph ---
  // ponytail: show every 3rd hour to fit. Size 1 dot text.
  const int16_t labelY = graphBottom + 5;
  for (uint8_t i = 0; i < n; i += 3) {
    int16_t x = graphX + (int16_t)(graphW * i) / (n - 1);
    char buf[8];
    snprintf(buf, sizeof(buf), "%02d", fc.hour[i]);
    // Center the 2-char label on the data point
    drawText7seg(canvas, buf, x - 6, labelY, 1, 0x7BEF); // gray, size 1
  }

  // --- Legend + location (single row at y=218) ---
  // ponytail: 12x12 1-bit icons replace the old square/line swatches.
  // Icons are sized to match the former swatch footprint so the row layout
  // is unchanged. Ceiling: 12px is tight for detail; glyphs are simple
  // enough to read at this size.
  const int16_t legendY = 218;
  const int16_t legendIcon = 12;

  // Precipitation (was blue square) — droplet icon in precip color
  canvas->drawBitmap(10, legendY, LICON_DROPLETS, legendIcon, legendIcon, PRECIP_COLOR);
  drawText7seg(canvas, "Rain", 28, legendY - 2, 1, 0x7BEF);

  // Temperature (was red line) — thermometer icon in temp color
  canvas->drawBitmap(90, legendY, LICON_THERMOMETER, legendIcon, legendIcon, TEMP_COLOR);
  drawText7seg(canvas, "Temp", 108, legendY - 2, 1, 0x7BEF);

  // --- Location (right-aligned) with map-pin icon ---
  const char *locStr = "Copenhagen";
  const int16_t locX = canvas->width() - 90;
  drawText7seg(canvas, locStr, locX, legendY - 2, 1, 0x7BEF);
  // Pin sits just left of the city name, vertically centered on the text row
  canvas->drawBitmap(locX - legendIcon - 2, legendY, LICON_MAP_PIN, legendIcon, legendIcon, 0x7BEF);

  pushToDisplay();
}

// ponytail: crude RGB565 channel-wise lerp. Not gamma-correct, but you can't
// tell the difference on a 1.91" AMOLED during a 200ms animation.
static uint16_t lerp565(uint16_t a, uint16_t b, float t) {
  int ra = (a >> 11) & 0x1F, ga = (a >> 5) & 0x3F, ba = a & 0x1F;
  int rb = (b >> 11) & 0x1F, gb = (b >> 5) & 0x3F, bb = b & 0x1F;
  int r  = ra + (int)((rb - ra) * t);
  int g  = ga + (int)((gb - ga) * t);
  int bl = ba + (int)((bb - ba) * t);
  return (uint16_t)((r << 11) | (g << 5) | bl);
}

void DisplayManager::drawWifiConnecting() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Pulse: 0..1 oscillation, ~1.9s period
  float phase = sinf(millis() / 300.0f) * 0.5f + 0.5f;
  uint16_t iconColor = lerp565(0x2104, 0x07FF, phase); // dark gray -> bright cyan

  // Centered 48x48 wifi icon, slightly above center to leave room for text
  int16_t iconX = (canvas->width() - 48) / 2;   // 244
  int16_t iconY = (canvas->height() - 48) / 2 - 15; // 81
  canvas->drawBitmap(iconX, iconY, ICON_WIFI_48, 48, 48, iconColor);

  // "Connecting..." text below
  const char *msg = "Connecting...";
  uint16_t w, h;
  text7segBounds(msg, 2, &w, &h);
  drawText7seg(canvas, msg, (canvas->width() - w) / 2, iconY + 48 + 10, 2,
          0x7BEF); // gray

  pushToDisplay();
}

void DisplayManager::drawConfigMenu(uint8_t selectedIndex) {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  drawText7seg(canvas, "CONFIG", 10, 10, 3, 0xFFE0); // yellow

  const uint8_t count = MenuManager::configItemCount();
  // ponytail: hard-coded vertical list spacing. Works for the current 1–3 items;
  // beyond that the list overflows the 240px height and needs scrolling.
  const int16_t startY = 80;
  const int16_t itemH  = 55;

  for (uint8_t i = 0; i < count; i++) {
    int16_t y = startY + i * itemH;
    const char* label = MenuManager::configItemLabel(i);
    bool sel = (i == selectedIndex);
    uint16_t col = sel ? 0x07FF : 0x7BEF;
    uint16_t bulletCol = sel ? 0x07FF : 0x4208;

    // Bullet
    canvas->fillCircle(15, y + 12, 5, bulletCol);

    // Label
    drawText7seg(canvas, label, 35, y, 3, col);

    // Icon for the Wi-Fi setup item; uses the same Wi-Fi bitmaps as the status screen.
    if (i == 0) {
      uint8_t iw = 0, ih = 0;
      const unsigned char* bm = menuIconBitmap(4, sel ? 48 : 32, &iw, &ih);
      if (bm) {
        int16_t ix = canvas->width() - iw - 10;
        int16_t iy = y + (itemH - ih) / 2;
        canvas->drawBitmap(ix, iy, bm, iw, ih, col);
      }
    }
  }

  pushToDisplay();
}

void DisplayManager::drawWifiPortalScreen() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  const char* title = "WIFI SETUP";
  uint16_t w, h;
  text7segBounds(title, 3, &w, &h);
  drawText7seg(canvas, title, (canvas->width() - w) / 2, 15, 3, 0x07FF); // cyan

  // Wi-Fi icon
  int16_t iconX = (canvas->width() - 48) / 2;
  int16_t iconY = 70;
  canvas->drawBitmap(iconX, iconY, ICON_WIFI_48, 48, 48, 0x07FF);

  // Instructions
  const char* line1 = "Connect to: W5-Setup";
  const char* line2 = "Open 192.168.4.1";
  const char* line3 = "Enter Wi-Fi details";

  text7segBounds(line1, 2, &w, &h);
  drawText7seg(canvas, line1, (canvas->width() - w) / 2, iconY + 48 + 20, 2, 0xFFFF);
  text7segBounds(line2, 2, &w, &h);
  drawText7seg(canvas, line2, (canvas->width() - w) / 2, iconY + 48 + 45, 2, 0xFFFF);
  text7segBounds(line3, 2, &w, &h);
  drawText7seg(canvas, line3, (canvas->width() - w) / 2, iconY + 48 + 70, 2, 0x7BEF);

  pushToDisplay();
}

void DisplayManager::drawWifiResultScreen(bool connected, const String &message) {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // Title
  const char* title = "WIFI SETUP";
  uint16_t w, h;
  text7segBounds(title, 3, &w, &h);
  drawText7seg(canvas, title, (canvas->width() - w) / 2, 15, 3, 0x07FF);

  // Status icon
  int16_t iconX = (canvas->width() - 48) / 2;
  int16_t iconY = 60;
  uint16_t iconCol = connected ? 0x07E0 : 0xF800;
  canvas->drawBitmap(iconX, iconY, ICON_WIFI_48, 48, 48, iconCol);

  // Status word
  const char* status = connected ? "Connected" : "Failed";
  text7segBounds(status, 3, &w, &h);
  drawText7seg(canvas, status, (canvas->width() - w) / 2, iconY + 48 + 15, 3,
          iconCol);

  // Message (truncated to screen width)
  String msg = message;
  if (msg.length() > 32) {
    msg = msg.substring(0, 29) + "...";
  }
  text7segBounds(msg.c_str(), 2, &w, &h);
  drawText7seg(canvas, msg.c_str(), (canvas->width() - w) / 2, iconY + 48 + 55, 2,
          0xFFFF);

  pushToDisplay();
}

// ponytail: MM:SS.CC from milliseconds. Caps at 99 minutes; a wrist stopwatch
// session rarely exceeds that. Ceiling: rolls over at 100 min. Upgrade: hours.
static String formatSw(uint32_t ms) {
  uint32_t totalCs = ms / 10;
  uint32_t s = totalCs / 100;
  uint32_t m = s / 60;
  uint32_t cs = totalCs % 100;
  s = s % 60;
  m = m % 100;
  char buf[12];
  snprintf(buf, sizeof(buf), "%02u:%02u.%02u", (unsigned)m, (unsigned)s, (unsigned)cs);
  return String(buf);
}

void DisplayManager::drawStopwatch() {
  if (!canvas)
    return;

  canvas->fillScreen(0x0000);

  // ----- Status label (top, centered) -----
  const char *status;
  uint16_t statusColor;
  if (StopwatchManager::isRunning()) {
    status = "RUNNING";
    statusColor = 0x07E0; // green
  } else if (StopwatchManager::isStopped()) {
    status = "STOPPED";
    statusColor = 0xF800; // red
  } else {
    status = "READY";
    statusColor = 0x07FF; // cyan
  }

  uint16_t w, h;
  text7segBounds(status, 2, &w, &h);
  drawText7seg(canvas, status, (canvas->width() - w) / 2, 12, 2, statusColor);

  // ----- Big elapsed time (centered, textSize 8) -----
  String timeStr = formatSw(StopwatchManager::getElapsedMs());
  text7segBounds(timeStr.c_str(), 8, &w, &h);
  drawText7seg(canvas, timeStr.c_str(), (canvas->width() - w) / 2,
          (canvas->height() - h) / 2, 8, 0xFFFF); // white

  // ----- Lap line (below time) or controls hint -----
  uint8_t laps = StopwatchManager::getLapCount();
  if (laps > 0) {
    String lapStr = "LAP " + String(laps) + ": " + formatSw(StopwatchManager::getLastLapMs());
    text7segBounds(lapStr.c_str(), 2, &w, &h);
    drawText7seg(canvas, lapStr.c_str(), (canvas->width() - w) / 2, 170, 2,
            0xFFE0); // yellow
  }

  // Controls hint (bottom, tiny gray)
  const char *hint = "TOP:START/STOP  BOT:LAP/RST";
  text7segBounds(hint, 1, &w, &h);
  drawText7seg(canvas, hint, (canvas->width() - w) / 2, 222, 1, 0x7BEF); // gray

  pushToDisplay();
}

// ===== Rotary menu — multi-style renderer =====
// ponytail: four visual styles share the same scroll math + label/icon rendering;
// each style owns its background, dot treatment, and ambient overlay. Style is
// selected at runtime via the CONFIG sub-menu and persisted in NVS. All styles
// use millis()-driven ambient animation (pulse/sweep/scanlines/flicker), so the
// main loop redraws MODE_MENU at ~20fps even when idle (see W5.ino).

// Shared geometry: half-arc hugging the left edge, vertically centered.
static const int16_t MENU_CX = 0;
static const int16_t MENU_CY = 120;  // canvas->height()/2 at 536x240
static const int16_t MENU_R  = 115;

// One item's computed position along the arc.
struct MenuItemPos { float angle; uint8_t idx; float closeness; };

// Compute the visible items for the current scroll state. Returns count written.
// Static (scrollDir==0): 3 items at -60/0/+60. Animated: up to 4 sliding items.
static int computeMenuItems(uint8_t selectedIndex, int8_t scrollDir, float t,
                            uint8_t count, MenuItemPos out[4]) {
  if (scrollDir == 0) {
    float angles[3] = { -60.0f, 0.0f, 60.0f };
    uint8_t idx[3] = {
      (uint8_t)((selectedIndex + count - 1) % count),
      selectedIndex,
      (uint8_t)((selectedIndex + 1) % count)
    };
    for (int i = 0; i < 3; i++) {
      out[i].angle = angles[i];
      out[i].idx = idx[i];
      out[i].closeness = (i == 1) ? 1.0f : 0.0f;
    }
    return 3;
  }
  // Animated: 4 items slide along the arc (see original comments in drawMenu).
  float shift = -scrollDir * 60.0f * t;
  uint8_t itemIdx[4];
  float baseAngles[4];
  if (scrollDir > 0) {
    itemIdx[0] = (selectedIndex + count - 2) % count;
    itemIdx[1] = (selectedIndex + count - 1) % count;
    itemIdx[2] = selectedIndex;
    itemIdx[3] = (selectedIndex + 1) % count;
    baseAngles[0] = -60; baseAngles[1] = 0; baseAngles[2] = 60; baseAngles[3] = 120;
  } else {
    itemIdx[0] = (selectedIndex + count - 1) % count;
    itemIdx[1] = selectedIndex;
    itemIdx[2] = (selectedIndex + 1) % count;
    itemIdx[3] = (selectedIndex + 2) % count;
    baseAngles[0] = -120; baseAngles[1] = -60; baseAngles[2] = 0; baseAngles[3] = 60;
  }
  int n = 0;
  for (int i = 0; i < 4; i++) {
    float angle = baseAngles[i] + shift;
    if (angle < -95.0f || angle > 95.0f) continue;
    out[n].angle = angle;
    out[n].idx = itemIdx[i];
    out[n].closeness = 1.0f - fabs(angle) / 60.0f;
    n++;
  }
  return n;
}

// Shared label + icon renderer (the 3-tier logic from the original drawMenuItem).
// Drawn left-anchored at the arc point (ax,ay), extending toward the outer edge.
// Far items get a faked 3-offset blur; near/selected get the icon to the right.
static void drawMenuLabel(GFXcanvas16 *c, int16_t ax, int16_t ay,
                          uint8_t labelIdx, float closeness) {
  if (closeness < 0.0f) closeness = 0.0f;
  if (closeness > 1.0f) closeness = 1.0f;
  String label(MenuManager::menuItemLabel(labelIdx));
  bool isSelected = (closeness >= 0.6f);
  bool isFar      = (closeness < 0.25f);
  uint8_t  textSize = isSelected ? 6 : (isFar ? 2 : 4);
  uint16_t textCol  = lerp565(0x4208, 0xFFFF, closeness);
  uint16_t w, h;
  text7segBounds(label.c_str(), textSize, &w, &h);
  int16_t tx = ax;
  int16_t ty = ay - (int16_t)h / 2;
  if (isFar) {
    uint16_t blurCol = lerp565(0x2104, 0x4208, closeness * 4.0f);
    drawText7seg(c, label.c_str(), tx,     ty,     textSize, blurCol);
    drawText7seg(c, label.c_str(), tx + 1, ty,     textSize, blurCol);
    drawText7seg(c, label.c_str(), tx,     ty + 1, textSize, blurCol);
  } else {
    drawText7seg(c, label.c_str(), tx, ty, textSize, textCol);
    uint8_t iconSize = isSelected ? 48 : 32;
    uint8_t iw = 0, ih = 0;
    const unsigned char *bm = menuIconBitmap(labelIdx, iconSize, &iw, &ih);
    if (bm) {
      int16_t iconX = tx + (int16_t)w + 4;
      int16_t iconY = ay - (int16_t)ih / 2;
      c->drawBitmap(iconX, iconY, bm, iw, ih, textCol);
    }
  }
}

// --- Style HUD: tactical compass ---
// Tick gauge around the arc + sweeping radar line with fading trail + reticle
// brackets around the selected dot + "02/04" index readout top-right.
static void drawMenuHUD(GFXcanvas16 *c, uint8_t selectedIndex, int8_t scrollDir, float t) {
  const int16_t cx = MENU_CX, cy = MENU_CY, r = MENU_R;
  const uint16_t arcColor = 0x07FF;
  // base arc
  c->drawCircle(cx, cy, r - 1, arcColor);
  c->drawCircle(cx, cy, r,     arcColor);
  c->drawCircle(cx, cy, r + 1, arcColor);
  // tick gauge: every 3deg around the half-arc, majors at ±60/0
  for (int a = -90; a <= 90; a += 3) {
    float rad = a * M_PI / 180.0f;
    bool major = (a % 60 == 0);
    int16_t tickLen = major ? 12 : 5;
    uint16_t col = major ? 0x07FF : 0x4208;
    int16_t x0 = cx + (int16_t)((r + 4) * cosf(rad));
    int16_t y0 = cy + (int16_t)((r + 4) * sinf(rad));
    int16_t x1 = cx + (int16_t)((r + 4 + tickLen) * cosf(rad));
    int16_t y1 = cy + (int16_t)((r + 4 + tickLen) * sinf(rad));
    c->drawLine(x0, y0, x1, y1, col);
  }
  // radar sweep: full revolution ~4s when idle; centered during scroll.
  // ponytail: trail faked with 5 dimmer line copies behind the sweep head —
  // no alpha on Adafruit_GFX, so we lerp toward black for the fade.
  float sweepDeg = (scrollDir != 0) ? 0.0f
                  : fmodf(millis() / 22.0f, 180.0f) - 90.0f;
  for (int k = 0; k < 5; k++) {
    float a = (sweepDeg - k * 7.0f) * M_PI / 180.0f;
    float intensity = (k == 0) ? 1.0f : (0.5f - k * 0.1f);
    uint16_t col = lerp565(0x0000, 0x07FF, intensity);
    int16_t ex = cx + (int16_t)((r + 18) * cosf(a));
    int16_t ey = cy + (int16_t)((r + 18) * sinf(a));
    c->drawLine(cx, cy, ex, ey, col);
  }
  // items
  const uint8_t count = MenuManager::menuItemCount();
  MenuItemPos items[4];
  int n = computeMenuItems(selectedIndex, scrollDir, t, count, items);
  for (int i = 0; i < n; i++) {
    float a = items[i].angle * M_PI / 180.0f;
    int16_t ax = cx + (int16_t)(r * cosf(a));
    int16_t ay = cy + (int16_t)(r * sinf(a));
    float cl = items[i].closeness;
    bool sel = (cl >= 0.6f);
    uint16_t dotColor = lerp565(0x2104, 0x07FF, cl);
    uint8_t dotRad = 2 + (uint8_t)(cl * 4.0f + 0.5f);
    if (sel) {  // pulse
      float pulse = sinf(millis() / 200.0f) * 0.5f + 0.5f;
      dotRad += (uint8_t)(pulse * 2.0f);
    }
    c->fillCircle(ax, ay, dotRad, dotColor);
    if (sel) drawCornerBrackets(c, ax - 11, ay - 11, 22, 22, 5, 0x07FF);
    drawMenuLabel(c, ax, ay, items[i].idx, cl);
  }
  // index readout top-right
  char buf[8];
  snprintf(buf, sizeof(buf), "%02u/%02u", selectedIndex + 1, count);
  drawText7seg(c, buf, c->width() - 70, 8, 2, 0x07FF);
}

// Filled arc segment between two radii (no drawArc in Adafruit_GFX; faked with
// radial lines at 2deg steps). Used by Holo for the lit selected slot.
static void drawArcSegment(GFXcanvas16 *c, int16_t cx, int16_t cy,
                           int16_t rInner, int16_t rOuter,
                           float centerDeg, float halfSpanDeg, uint16_t color) {
  for (float a = centerDeg - halfSpanDeg; a <= centerDeg + halfSpanDeg; a += 2.0f) {
    float rad = a * M_PI / 180.0f;
    int16_t x0 = cx + (int16_t)(rInner * cosf(rad));
    int16_t y0 = cy + (int16_t)(rInner * sinf(rad));
    int16_t x1 = cx + (int16_t)(rOuter * cosf(rad));
    int16_t y1 = cy + (int16_t)(rOuter * sinf(rad));
    c->drawLine(x0, y0, x1, y1, color);
  }
}

// --- Style Holo: holographic ring ---
// Double ring with lit segment at the selected slot + CRT scanlines +
// pulsing dot.
static void drawMenuHolo(GFXcanvas16 *c, uint8_t selectedIndex, int8_t scrollDir, float t) {
  const int16_t cx = MENU_CX, cy = MENU_CY, r = MENU_R;
  const int16_t rIn = r - 8, rOut = r + 8;
  // dim band between rings
  drawArcSegment(c, cx, cy, rIn, rOut, 0, 90, 0x2104);
  // ring outlines
  c->drawCircle(cx, cy, rIn,  0x4208);
  c->drawCircle(cx, cy, rOut, 0x4208);
  // CRT scanlines: every 3rd row a dim horizontal line over the menu area.
  // ponytail: cheap CRT texture — 80 drawFastHLine calls, no per-pixel work.
  for (int16_t y = 0; y < c->height(); y += 3)
    c->drawFastHLine(0, y, c->width(), 0x2104);
  // items
  const uint8_t count = MenuManager::menuItemCount();
  MenuItemPos items[4];
  int n = computeMenuItems(selectedIndex, scrollDir, t, count, items);
  for (int i = 0; i < n; i++) {
    float a = items[i].angle * M_PI / 180.0f;
    int16_t ax = cx + (int16_t)(r * cosf(a));
    int16_t ay = cy + (int16_t)(r * sinf(a));
    float cl = items[i].closeness;
    bool sel = (cl >= 0.6f);
    // lit segment follows the selected item's angle
    if (sel) {
      float segCenter = items[i].angle;
      drawArcSegment(c, cx, cy, rIn, rOut, segCenter, 22.0f, 0x07FF);
    }
    // dot with pulse on selected
    uint16_t dotColor = lerp565(0x2104, 0x07FF, cl);
    uint8_t dotRad = 2 + (uint8_t)(cl * 4.0f + 0.5f);
    if (sel) {
      float pulse = sinf(millis() / 200.0f) * 0.5f + 0.5f;
      dotRad += (uint8_t)(pulse * 2.0f);
    }
    c->fillCircle(ax, ay, dotRad, dotColor);
    drawMenuLabel(c, ax, ay, items[i].idx, cl);
  }
}

// --- Style Data: data stream ---
// Connecting circuit trace between visible dots + per-item telemetry columns +
// horizontal lock-on bar from the selected label to the right edge with a
// moving highlight segment. Telemetry values flicker via millis().
static void drawMenuData(GFXcanvas16 *c, uint8_t selectedIndex, int8_t scrollDir, float t) {
  const int16_t cx = MENU_CX, cy = MENU_CY, r = MENU_R;
  c->drawCircle(cx, cy, r, 0x4208);  // dim base arc
  const uint8_t count = MenuManager::menuItemCount();
  MenuItemPos items[4];
  int n = computeMenuItems(selectedIndex, scrollDir, t, count, items);
  // circuit trace: polyline connecting all visible dots (dim)
  if (n >= 2) {
    for (int i = 0; i < n - 1; i++) {
      float a0 = items[i].angle * M_PI / 180.0f;
      float a1 = items[i + 1].angle * M_PI / 180.0f;
      int16_t x0 = cx + (int16_t)(r * cosf(a0));
      int16_t y0 = cy + (int16_t)(r * sinf(a0));
      int16_t x1 = cx + (int16_t)(r * cosf(a1));
      int16_t y1 = cy + (int16_t)(r * sinf(a1));
      c->drawLine(x0, y0, x1, y1, 0x4208);
    }
  }
  // ponytail: per-item pseudo-telemetry. Values derived from millis()+idx so they
  // flicker but stay in plausible ranges. Pure cosmetic — not real sensor data.
  static const char* const TELE_L1[] = { "HR 72", "LAP 03", "21C",  "NVS OK" };
  static const char* const TELE_L2[] = { "STEPS 8421", "BEST 42", "HUM 64", "VER 1.0" };
  for (int i = 0; i < n; i++) {
    float a = items[i].angle * M_PI / 180.0f;
    int16_t ax = cx + (int16_t)(r * cosf(a));
    int16_t ay = cy + (int16_t)(r * sinf(a));
    float cl = items[i].closeness;
    bool sel = (cl >= 0.6f);
    bool isFar = (cl < 0.25f);
    // dot
    uint16_t dotColor = lerp565(0x2104, 0x07FF, cl);
    uint8_t dotRad = 2 + (uint8_t)(cl * 4.0f + 0.5f);
    if (sel) {
      float pulse = sinf(millis() / 200.0f) * 0.5f + 0.5f;
      dotRad += (uint8_t)(pulse * 2.0f);
    }
    c->fillCircle(ax, ay, dotRad, dotColor);
    drawMenuLabel(c, ax, ay, items[i].idx, cl);
    // telemetry column under the label (near/selected only)
    if (!isFar) {
      uint8_t idx = items[i].idx;
      // flicker: dim/bright toggle every ~400ms, offset per item
      bool flicker = ((millis() + idx * 137) / 400) % 2 == 0;
      uint16_t tcol = flicker ? lerp565(0x4208, 0x07E0, cl) : 0x4208;
      int16_t ty = ay + (sel ? 30 : 20);
      drawText7seg(c, TELE_L1[idx], ax, ty, 1, tcol);
      drawText7seg(c, TELE_L2[idx], ax, ty + 14, 1, 0x4208);
    }
    // lock-on bar from selected label to right edge with moving highlight
    if (sel) {
      int16_t barY = ay;
      c->drawFastHLine(ax, barY, c->width() - ax, 0x4208);
      // moving 30px bright segment, ~1.5s traversal
      int16_t span = c->width() - ax;
      int16_t segPos = (int16_t)(fmodf(millis() / 1500.0f, 1.0f) * span);
      c->drawFastHLine(ax + segPos, barY, 30, 0x07FF);
    }
  }
}

// --- Style Minimal: minimal sci-fi ---
// Marching-ants dashed arc + glow halo around selected dot + bracket-wrapped
// selected label + subtle inner border. Subtle, lowest visual noise.
static void drawMenuMinimal(GFXcanvas16 *c, uint8_t selectedIndex, int8_t scrollDir, float t) {
  const int16_t cx = MENU_CX, cy = MENU_CY, r = MENU_R;
  // marching-ants dashed arc: 4px on / 4px off, phase rotates with millis().
  // ponytail: Adafruit_GFX has no dashed-circle, so we step around the half-arc
  // in 2deg increments and draw short arc chords for "on" segments. ~45 calls.
  float phase = fmodf(millis() / 400.0f, 8.0f);  // 0..8, wraps
  for (int a = -90; a <= 90; a += 2) {
    float pos = fmodf(a + 90 + phase, 8.0f);  // 0..8 along the dash cycle
    if (pos >= 4.0f) continue;  // gap
    float rad0 = a * M_PI / 180.0f;
    float rad1 = (a + 2) * M_PI / 180.0f;
    int16_t x0 = cx + (int16_t)(r * cosf(rad0));
    int16_t y0 = cy + (int16_t)(r * sinf(rad0));
    int16_t x1 = cx + (int16_t)(r * cosf(rad1));
    int16_t y1 = cy + (int16_t)(r * sinf(rad1));
    c->drawLine(x0, y0, x1, y1, 0x07FF);
  }
  // subtle inner border
  c->drawRect(2, 2, c->width() - 4, c->height() - 4, 0x2104);
  const uint8_t count = MenuManager::menuItemCount();
  MenuItemPos items[4];
  int n = computeMenuItems(selectedIndex, scrollDir, t, count, items);
  for (int i = 0; i < n; i++) {
    float a = items[i].angle * M_PI / 180.0f;
    int16_t ax = cx + (int16_t)(r * cosf(a));
    int16_t ay = cy + (int16_t)(r * sinf(a));
    float cl = items[i].closeness;
    bool sel = (cl >= 0.6f);
    // glow halo: 3 concentric circles, dimmer outward (selected only)
    if (sel) {
      float pulse = sinf(millis() / 300.0f) * 0.5f + 0.5f;
      c->fillCircle(ax, ay, 10 + (int16_t)(pulse * 2), 0x2104);
      c->drawCircle(ax, ay, 9,  0x4208);
      c->drawCircle(ax, ay, 12, 0x2104);
    }
    uint16_t dotColor = lerp565(0x2104, 0x07FF, cl);
    uint8_t dotRad = 2 + (uint8_t)(cl * 4.0f + 0.5f);
    c->fillCircle(ax, ay, dotRad, dotColor);
    // bracket-wrapped label for selected: "( WATCH )"
    // ponytail: 7-seg font has no []/<>, only (). We wrap the label in parens.
    if (sel) {
      String label(MenuManager::menuItemLabel(items[i].idx));
      uint16_t w, h;
      text7segBounds(label.c_str(), 6, &w, &h);
      int16_t ty = ay - (int16_t)h / 2;
      drawText7seg(c, "(", ax - 18, ty, 6, 0x07FF);
      drawText7seg(c, ")", ax + (int16_t)w + 6, ty, 6, 0x07FF);
    }
    drawMenuLabel(c, ax, ay, items[i].idx, cl);
  }
}

void DisplayManager::drawMenu(uint8_t selectedIndex, int8_t scrollDir, float t) {
  if (!canvas)
    return;
  canvas->fillScreen(0x0000);
  switch (MenuManager::menuStyle()) {
    case STYLE_HUD:     drawMenuHUD(canvas, selectedIndex, scrollDir, t);     break;
    case STYLE_HOLO:    drawMenuHolo(canvas, selectedIndex, scrollDir, t);    break;
    case STYLE_DATA:    drawMenuData(canvas, selectedIndex, scrollDir, t);    break;
    case STYLE_MINIMAL: drawMenuMinimal(canvas, selectedIndex, scrollDir, t); break;
    default:            drawMenuHUD(canvas, selectedIndex, scrollDir, t);     break;
  }
  pushToDisplay();
}

// ponytail: dive/zoom transition. A bracket contracts from fullscreen into a
// small rect at the selected menu item's arc position (phase 1), then expands
// back to fullscreen (phase 2). The content inside is just the item label —
// not a full screen redraw. The full menu/watch/weather renderers take 15-30ms
// each, which plus the 27ms SPI push gave only 6-8 frames over the 350ms
// animation (smoothstep has zero velocity at endpoints → bracket appeared
// frozen for 100ms+ at start/end). Drawing just a label drops content draw to
// ~1ms, giving ~12 frames. The real screen draws when the transition resolves.
void DisplayManager::drawTransition(uint8_t selectedIndex, float progress) {
  if (!canvas) return;
  GFXcanvas16 *c = canvas;

  // Selected item center on the menu arc (angle = 0).
  const int16_t sx = MENU_CX + MENU_R;  // 115
  const int16_t sy = MENU_CY;           // 120
  const int16_t tw = 24, th = 24;
  const int16_t tx = sx - tw / 2, ty = sy - th / 2;
  const int16_t fw = c->width(), fh = c->height();

  const bool phase1 = (progress < 0.5f);
  const float p = phase1 ? (progress * 2.0f) : ((progress - 0.5f) * 2.0f);

  auto lerpI = [](int16_t a, int16_t b, float t) {
    return (int16_t)(a + (b - a) * t + 0.5f);
  };

  int16_t rx, ry, rw, rh;
  if (phase1) {
    rx = lerpI(0, tx, p);  ry = lerpI(0, ty, p);
    rw = lerpI(fw, tw, p); rh = lerpI(fh, th, p);
  } else {
    rx = lerpI(tx, 0, p);  ry = lerpI(ty, 0, p);
    rw = lerpI(tw, fw, p); rh = lerpI(th, fh, p);
  }

  // Content: just the selected item label, centered. Color shifts cyan→yellow
  // at the midpoint to signal the content swap without an expensive redraw.
  c->fillScreen(0x0000);
  const char* label = MenuManager::menuItemLabel(selectedIndex);
  uint16_t labelCol = phase1 ? 0x07FF : 0xFFE0;  // cyan → yellow
  uint16_t lw, lh;
  text7segBounds(label, 4, &lw, &lh);
  drawText7seg(c, label, (fw - lw) / 2, (fh - lh) / 2, 4, labelCol);

  // Mask outside the bracket rect with black (4 strips).
  c->fillRect(0, 0, fw, ry, 0x0000);                  // top
  c->fillRect(0, ry + rh, fw, fh - (ry + rh), 0x0000); // bottom
  c->fillRect(0, ry, rx, rh, 0x0000);                 // left
  c->fillRect(rx + rw, ry, fw - (rx + rw), rh, 0x0000); // right

  // Bracket outline: solid cyan in phase 1, fading out in phase 2.
  uint16_t bracketCol = phase1 ? 0x07FF : lerp565(0x07FF, 0x0000, p);
  if (bracketCol != 0x0000)
    drawCornerBrackets(c, rx, ry, rw, rh, 6, bracketCol);

  pushToDisplay();
}

// Menu style picker sub-screen. Lists the 4 styles; the live cursor is
// highlighted in cyan. Title + hint at top, current applied style marked.
void DisplayManager::drawMenuStylePicker(uint8_t pickerIndex) {
  if (!canvas)
    return;
  GFXcanvas16 *c = canvas;
  c->fillScreen(0x0000);

  // Title
  drawText7seg(c, "MENU STYLE", 10, 10, 3, 0xFFE0);  // yellow

  const uint8_t count = MenuManager::menuStyleCount();
  const MenuStyle applied = MenuManager::menuStyle();
  const int16_t startY = 70;
  const int16_t itemH  = 38;

  for (uint8_t i = 0; i < count; i++) {
    int16_t y = startY + i * itemH;
    const char* label = MenuManager::menuStyleLabel(i);
    bool sel = (i == pickerIndex);
    bool isApplied = (i == (uint8_t)applied);
    uint16_t col = sel ? 0x07FF : 0x7BEF;
    uint16_t bulletCol = sel ? 0x07FF : 0x4208;

    // Bullet
    c->fillCircle(15, y + 12, 5, bulletCol);
    // Label
    drawText7seg(c, label, 35, y, 3, col);
    // "(current)" marker on the applied style — small filled dot (no * glyph)
    if (isApplied) {
      c->fillCircle(c->width() - 14, y + 12, 4, 0xFFE0);
    }
    // reticle around the selected row
    if (sel) drawCornerBrackets(c, 6, y - 4, c->width() - 12, itemH - 4, 4, 0x07FF);
  }

  // Hint
  drawText7seg(c, "DBL CLICK APPLY   BOTH BACK", 10, c->height() - 16, 1, 0x7BEF);

  pushToDisplay();
}

void DisplayManager::drawBrightnessPicker(uint8_t pickerIndex) {
  if (!canvas)
    return;
  GFXcanvas16 *c = canvas;
  c->fillScreen(0x0000);

  // Title
  drawText7seg(c, "BRIGHTNESS", 10, 10, 3, 0xFFE0);  // yellow

  // ponytail: 16-segment horizontal bar. Each filled segment = one level.
  // segW/gap chosen so the bar spans most of the 536px width.
  const uint8_t segs = BRIGHTNESS_LEVELS;
  const int16_t segW = 29, gap = 2;
  const int16_t barW = segs * segW + (segs - 1) * gap;  // 494
  const int16_t barX = (c->width() - barW) / 2;         // centered
  const int16_t barY = 110;
  const int16_t barH = 30;

  const uint8_t applied = MenuManager::brightness();

  for (uint8_t i = 0; i < segs; i++) {
    int16_t x = barX + i * (segW + gap);
    // ponytail: level N fills N of 16 segments. Level 0 = empty (panel off),
    // level 15 = 15/16 filled (reads as "near max"). Consistent 1:1 mapping.
    bool filled = (i < pickerIndex);
    uint16_t col = filled ? 0x07FF : 0x2104;       // cyan filled, dim empty
    c->fillRect(x, barY, segW, barH, col);
  }

  // Reticle around the whole bar
  drawCornerBrackets(c, barX - 6, barY - 6, barW + 12, barH + 12, 5, 0x07FF);

  // "(current)" marker on the applied level's segment
  if (applied < segs) {
    int16_t mx = barX + applied * (segW + gap) + segW / 2;
    c->fillCircle(mx, barY + barH + 12, 4, 0xFFE0);
  }

  // Numeric readout: level n/15 and DBV percentage
  char buf[16];
  snprintf(buf, sizeof(buf), "LVL %u/%u", pickerIndex, segs - 1);
  uint16_t w, h;
  text7segBounds(buf, 2, &w, &h);
  drawText7seg(c, buf, (c->width() - w) / 2, barY + barH + 30, 2, 0xFFFF);

  uint8_t pct = (uint8_t)((uint32_t)pickerIndex * 100 / (segs - 1));
  snprintf(buf, sizeof(buf), "%u%%", pct);
  text7segBounds(buf, 3, &w, &h);
  drawText7seg(c, buf, (c->width() - w) / 2, 60, 3, 0x07FF);

  // Hint
  drawText7seg(c, "DBL CLICK APPLY   BOTH BACK", 10, c->height() - 16, 1, 0x7BEF);

  pushToDisplay();
}
